### ISSUE TITLE
Augment documentation of model steps

### ISSUE THREAD

**Issue by bstabler** [ActivitySim/activitysim#138]
@e-lo 

Augment documentation of model steps to include:
  - Key inputs, required fields, expected formats, and required fields
  - What settings and parameters files it uses
  - Where it fits in the grand model run
  - Where outputs are expected and how can I summarize the results quickly using API?
  - Re-organize and further document “helper” files
  - Re-think/name files with similar file names in sub-folders. For example, test and tests; misc.py and - util/misc.py, etc.
  - Create consistency in file structure and functions.
  - Create and document a “model step recipe” that is consistent in structure and documentation requirements.

**Comment by dhensle** [comment]
Documentation updated with #647
