### ISSUE TITLE
auto post package to pypi

### ISSUE THREAD

**Issue by bstabler** [ActivitySim/activitysim#139]
Currently the ActivitySim package is manually posted to https://pypi.python.org/pypi/activitysim.  We should automate this process.

**Comment by bstabler** [comment]
We should also automatically set the version number in the docs/conf.py based on the version in setup.py

**Comment by bstabler** [comment]
@jpn-- are we thinking of adding this to #440?

**Comment by jpn--** [comment]
Yes, the new plan is to get at least this into #440.  I'm not yet sure if we can automate the entire release checklist within the budget for Phase 6b.

**Comment by bstabler** [comment]
this is now assigned to me to finalize with the pypi credentials

**Comment by bstabler** [comment]
this is now working
