### ISSUE TITLE
each model step should print something useful

### ISSUE THREAD

**Issue by bstabler** [ActivitySim/activitysim#157]
some model steps such as auto ownership print a [value_counts()](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.Series.value_counts.html) upon completion.  We should do this (and possibly require it) for each model step.  We may want to move all these prints into the log file instead.

**Comment by bstabler** [comment]
#397

**Comment by dhensle** [comment]
Closed in favor of #408
