### ISSUE TITLE
Python 3 compatibility 

### ISSUE THREAD

**Issue by bstabler** [ActivitySim/activitysim#206]
as suggested by @e-lo

**Comment by bstabler** [comment]
Python 2.7 will be retired Jan 1, 2020 - see https://pythonclock.org/

**Comment by guyrousseau** [comment]
Somewhat related to this, ArcGIS 10.5 requires Python 2.7.13.  It seems as if ESRI is running the clock out on Desktop, which 10.6 looks like the last version, which will prompt a switch over to Pro, which supports Python 3.x.

**Comment by bstabler** [comment]
[We decided](https://github.com/ActivitySim/activitysim/wiki/Project-Meeting-2018.10.05) to support both 2.7 and 3.   We will gradually make the [necessary updates](http://python-future.org/compatible_idioms.html) during the course of the Phase 4 work.
