### ISSUE TITLE
Error message misreports config dir as output and data dirs

### ISSUE THREAD

**Issue by lmz** [ActivitySim/activitysim#231]
https://github.com/ActivitySim/activitysim/blob/b9c51b94e3dae678eb493957e0c3bb307216fde8/activitysim/core/config.py#L48

https://github.com/ActivitySim/activitysim/blob/b9c51b94e3dae678eb493957e0c3bb307216fde8/activitysim/core/config.py#L52

**Comment by toliwaga** [comment]
Oops! Thanks Lisa. I fixed in the joint-tours I am working on, which I expect will be ready for release in a few days.
