### ISSUE TITLE
code and use person value of time in the example

### ISSUE THREAD

**Issue by bstabler** [ActivitySim/activitysim#237]
TM1 codes person VOT when reading in the synthetic population files.  The current asim example just uses a global VOT for mode choice expressions, etc.  So, we need to eventually:
  - code person (and household) VOT.  This could be either a new sub-model at the start or an annotation of persons and households before a sub-model.
  - update all the expression files to use the individual VOT

**Comment by joecastiglione** [comment]
Would be great to have trip-specific VOTs, based on income as well as other attributes such as trip purpose, occupancy, etc
