### ISSUE TITLE
ensure non-continuous zone IDs work

### ISSUE THREAD

**Issue by bstabler** [ActivitySim/activitysim#244]
Our current test case, TM1, was setup with a sequential 1 to N understanding of TAZs and therefore we may run into issues with non-continuous zone IDs found in other regions.

**Comment by toliwaga** [comment]
There is an OffsetMapper object in core.skim that supposedly handles this. (And is tested in a somewhat cursory way in core.test.test_skim.py)

But the SkimDict initialization call in abm.tables.skims currently doesn't pass it in because the mtctm1 test dataset doesn't require it.

**Comment by bstabler** [comment]
This has been confirmed to work with the new multiple zone system support in the release
