### ISSUE TITLE
improve shadow pricing configuration

### ISSUE THREAD

**Issue by bstabler** [ActivitySim/activitysim#252]
We currently have two similar, but slightly different, approaches to shadow pricing.  The "ctramp" approach from MTC TM1 and the "daysim" approach from DaySim.  They are similar, but once the modeled zone size gets close to the target, DaySim modifies the shadow price a bit differently + there are also some different user settings for each approach.  Eventually we might want to merge them into one procedure with multiple user configurable settings, drop the labels "ctramp" and "daysim", and make any additional algorithmic enhancements to improve performance and runtime.

**Comment by bstabler** [comment]
Let's not forgot this potential enhancement as well:

*from @wusun2*

Typically zonal employment is total employment by both residents and non-residents; while PopSyn is only residents.  Should we discount the non-resident portion of employment when balancing workers in PopSyn and employment?  Or the SP algorithm already takes care of this?  If not, for smaller study area (geographically), this could be an issue. 

*from @joecastiglione* 

In Daysim there is an TAZ-level input file (IXXIfractions.dat) that contains information on:

  -  The fraction of workers living in the zone who work outside the region

  -  The fraction of jobs in the zone filled by workers from outside the region

The former is used to select a sample of workers for whom to choose an in-region usual workplace destination.  The latter is used to reduce the target number of usual work locations in a zone chosen by regional resident workers.

**Comment by jfdman** [comment]
Closing this issue due to recent mandatory location choice simulation constraint enhancements in ActivitySim 1.2
