### ISSUE TITLE
specific pyyaml version needed

### ISSUE THREAD

**Issue by bstabler** [ActivitySim/activitysim#253]
The example throws a YAML error immediately because yaml.load without specifying the "Loader=" keyword argument is deprecated.  We need to update our usage of pyyaml or specify a specific version in setup.py.  See https://github.com/yaml/pyyaml/issues/265.

**Comment by bhargavasana** [comment]
I just tried running the example for the first time yesterday and encountered this error. Good to know that this is indeed an issue and that I wasn't running it incorrectly.

**Comment by bstabler** [comment]
This is now fixed in the `setup.py` file in the [verification-fixes](https://github.com/ActivitySim/activitysim/tree/verification-fixes) branch.  You can reinstall activitysim by cloning this branch and running `python setup.py develop`.  You may need to first `pip uninstall pyyaml`.  The [pypi version](https://pypi.org/project/activitysim/) of the package will be updated once we do an official release, which I expect to do within the next few weeks.
