### ISSUE TITLE
Provide better feedback when output_dir not found

### ISSUE THREAD

**Issue by toliwaga** [ActivitySim/activitysim#268]
If output_dir is not found, output_dir method in core/config.py 

`raise RuntimeError("output_dir: directory does not exist")`
resulting in the message:
`RuntimeError: output_dir: directory does not exist`

This is misleading because 'output_dir' is the name of the method raising the error, not the expected name of the directory it isn't finding. Instead, or in addition, should print path that wasn't found. e.g. something like:
`RuntimeError: output_dir: directory does not exist: F:\some_path\output`

**Comment by toliwaga** [comment]
Can't help wondering what the totemp destination zone matrix is? Maybe annotate with comment line in destination_choice.yaml config file?

**Comment by toliwaga** [comment]
I like the way the math functions are parameterized in the config file - we shold do something like this for activitysim? (would need to cascade to allow extensions?)

**Comment by toliwaga** [comment]
Should use same docstring format (numpydoc) as activitysim?

You can set a default in pycharm...

**Comment by toliwaga** [comment]
Will we want to support skim offsets or non-contiguous skim indexing? (i.e. OffsetMapper functionality)

is the skims object from bca4abm functionally the same as asim DataFrameMatrix? Or more to the point, do we have similar/overlapping functionality in asim, bca4abm, and here that should be rationalized/consolidated?

**Comment by bstabler** [comment]
#397
