### ISSUE TITLE
output_tables function also write hdf5 if desired

### ISSUE THREAD

**Issue by bstabler** [ActivitySim/activitysim#278]
Provide automatic generation of simpler and more typical activity-based model output files such as the final household, person, tour, and trip files. (which basically means adding a CSV or HDF5 option to the output_tables function)

https://github.com/ActivitySim/activitysim/blob/master/example/configs/settings.yaml#L72

**Comment by bettinardi** [comment]
Hi Ben, I'm interested in following and reviewing this.  I think we said that those that are closely following a topic would be assignees.  I'm currently not an allowed editor on the activitySim github repo, so I can't add myself.  What's the right course of action.? Can you add me?

**Comment by joecastiglione** [comment]
Alex,

We can make you an owner.

What's your github username?

Thanks,

Joe

**Comment by blakerosenthal** [comment]
## Task Spec

The [write_output_tables](https://github.com/ActivitySim/activitysim/blob/7b57c94e12d27a23f86c8988117e885ae754c44e/activitysim/core/steps/output.py#L183) step currently only handles CSV outputs. We will add the option to write all tables into a single HDF5 store of pandas DataFrames via [pandas.to_hdf](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_hdf.html). This option will be controlled in [settings.yaml](https://github.com/ActivitySim/activitysim/blob/master/example/configs/settings.yaml#L72) via a new subflag to `output_tables` called `h5_store`:
```
output_tables:
  h5_store: true
  action: include
  prefix: final_
  tables:
    - checkpoints
    ...
```
