### ISSUE TITLE
add interactive model developer tutorial

### ISSUE THREAD

**Issue by bstabler** [ActivitySim/activitysim#280]
We reviewed the [existing rst user documentation](https://activitysim.github.io/activitysim/gettingstarted.html) and the online runnable Google Colab Jupyter notebooks (which we recently created for [open matrix](https://colab.research.google.com/drive/1PUoNc1o-n1042F-xmTH9MEMxramvduHr)) and decided to create the tutorial in Jupyter notebooks, link to it from the rst user docs, and make sure to have a non-colab version/option so users can run it locally.  The next step is to draft an outline and share some similar examples.

**Comment by bstabler** [comment]
Being developed at https://colab.research.google.com/drive/1OAD7Vs47hkFIuayaEl6etDE3ixNx_Dul

**Comment by bettinardi** [comment]
Some reactions - 

There's a cloud version and a download version.  I'm not clear from the start of the tutorial what the instructions are guiding.  There should be extra text to really hand hold new people to activitysim and running in the cloud exactly what to do.  Make it really painfully simple.

Input and Output overview should include hyper links to more detail and description on each of these files.

**Comment by bstabler** [comment]
Will do, thanks

**Comment by bstabler** [comment]
Some additional requirements based on our 01/24/20 call
  - It will be integrated with the online user's guide to avoid duplication
  - Split into two tutorials - application (auto own example) and development (add TNCs)

**Comment by bstabler** [comment]
#325
