### ISSUE TITLE
add support for modeling TNCs and for-hire vehicles

### ISSUE THREAD

**Issue by bstabler** [ActivitySim/activitysim#282]
spec coming soon

**Comment by bstabler** [comment]
See https://github.com/ActivitySim/activitysim/wiki/Adding-TNCs-to-ActivitySim

**Comment by bettinardi** [comment]
Some reactions to looking over the current draft plan - 

It's unclear how much is intended to be embedded in the code.  Like tolls.  I think it's fine to have that as an option, but I wouldn't want the model to have a forced assumption that highway/bridge tolls apply to TNC / taxi.

Similar with skims, I wouldn't want to code to always assume that HOV2 skims should be used.  It should be a user input / configurable.

In general we should try and make the approach as parameterized as much as possible.  I think we can guarantee that this mode and it's characteristics will continue to change so we need flexibility with how this is configured.  I also would push away from representing too many specialized modes.  Like I wouldn't have taxi and TNC as separate modes, they seem close enough that for future work we don't need to worry about how many different flavors of shared (not owned) people movers there are.

Also, I want this development to continue to be aware of the need to represent TNC fleets and while this development effort won't have a TNC fleet model, it would be nice if it was constructed in away that could use information from a TNC scheduler / model, if it became available.  And just be aware in general that at somepoint in the model stream / development stream that TNC vehicles need to be developed and assigned...

**Comment by bstabler** [comment]
I updated the draft plan to say that the implementation will be done through expression files and settings files and so it will be very flexible.  Users can for example change the type of skims, add/drop tolls, change nesting coefficients and modes, change wait time functions, etc.

**Comment by guyrousseau** [comment]
As part of our regional transit on-board survey, we’re learning more about TNC / for-hire / ride-hailing (Uber / Lyft) as a mode of access and egress to and from transit.  Thus far, we have noticed that more transit passengers are getting to their origin and to their destination by more different types of modes.  This shows with walk access at only about 82% and walk egress at 84%.  This may also be due to the MARTA heavy rail, since many people drive and park, but we have been noticing a decent amount of people being dropped off as we go through the survey data.  With regards to TNC / Uber / Lyft as a mode of access, so far 35% of passengers state they would use TNC / Uber / Lyft if bus service were not available, and a good amount of passengers state they have used Uber / Lyft / TNC, however, only 2% of passengers are using these services to get to their first bus stop,  For more details, see  https://etcinstitute.com/transit/transit-dashboards/ga_arc/

**Comment by joecastiglione** [comment]
Guy,

Thanks so much for this info, and for sharing the link to the dashboard.

However, I'm sure I'm being an idiot, but I couldn't figure out how to find
the access/egress stats in the dashboard.  Any chance you have 5 min to
talk to set me straight?

Thanks again!

Joe


*Joe Castiglione*
Deputy Director for Technology, Data, and Analysis



sfcta.org <https://www.sfcta.org/> | sign up for our newsletter
<https://www.sfcta.org/stay-connected>

**Comment by guyrousseau** [comment]
The access / egress tabulations to and from transit are not readily available from the dashboard.  Those were simply cross-tabulated from a raw (preliminary) dataset.  

The dashboard is mostly for systemwide indicators, and serves more as a QA/QC monitoring type of tool to manage day-to-day data collection and operations.

**Comment by JilanChen** [comment]
SEMCOG is conducting a similar regional transit on-board survey like ARC’s. The preliminary data shows that the TNC (Uber/Lyft/etc.) as a mode of access and egress to and from transit is very small. With heavily walk access (91%) and egress (95%) in the region, only 0.15% of passengers are using the TNC service from their origin to their first bus stop or from their last bus stop to their destination. These numbers can be found in more details from SEMCOG’s transit dashboard https://etcinstitute.com/transit/transit-dashboards/mi_semcog/

**Comment by guyrousseau** [comment]
The Union of Concerned Scientists released a study last week estimating that Uber & Lyft generate 70% more pollution than the trips they replace, which are often times transit, bike, and/or walk trips, see interesting numbers and stats:
https://www.ucsusa.org/resources/ride-hailing-climate-risks
Something to keep in mind and account for when modeling TNCs within ActivitySim.

**Comment by bstabler** [comment]
#325
