### ISSUE TITLE
Consider new TOC for the wiki

### ISSUE THREAD

**Issue by bettinardi** [ActivitySim/activitysim#292]
As mentioned at the TRB meeting (1-14-20), I had suggested that the retrospective decisions of ActivitySim are structured on the wiki in a more meaningful way for people that weren't a part of the team / discussions.  It's currently structured by phase and is therefore only meaningful to members who have a rough understanding of what work occurred under each phase.

Joe correctly, asked if I had any thoughts or examples on what a better model to organize the content looks like.  I will continue to look for examples, but in absence of other examples, all I think that needs to be done is a restructure of the organization of the main page and the right sidebar TOC - https://github.com/activitysim/activitysim/wiki

I would suggest that the TOC be structured around:
  - Introduction / Governance / partners
  - What have we accomplished (listing the timeline and what has occurred)
  - Strategic Direction (where are we headed, what tasks are in the queue)
  - Current Active Work / Tasks and discussions

I think all the active scopes have pages under the current work TOC
Any completed work, get's properly archived in the historic timeline.  I think once a year there is a review of the text on the timeline page to update it with the latest completed work.  I think for the most part the historic work is an annotated outline of brief statements about the work completed with bullet links to all the pages that captured on the wiki during that work.

Also an end of the year task would be refreshing the direction and what projects/tasks are planned in Year X+1, X+2....

**Comment by joecastiglione** [comment]
In addition to the wiki, we also have activitysim.org.

We may want to consider publishing more marketing-type project collateral
(such as partners, non-technical narrative accomplishments, direction etc)
to activitysim.org

And directing more project management / technical collateral to
https://github.com/activitysim/activitysim/wiki.  I actually kinda like
having the current workscope at the top because it's typically the freshest
content that I want to reference.

Joe

**Comment by bettinardi** [comment]
I would echo the idea of having different purposes for the wiki versus activitysim.org.  I struggle with when/why I should visit either page.  I would propose that somewhere near the top of each of these pages it references the other and briefly highlights what one should expect to find on each (the wiki versus activitysim.org).

I would also echo the idea to have the most current activity at the top of the TOC on the wiki page.  I was thinking about this as well when I was drafting my ideas.  I still think we need to get away from phase references (at least in the TOC - phases can be discussed on the page content).  So I would suggest just a slight reordering of my proposed TOC:

  - Current Active Work / Tasks and discussions
  - Introduction / Governance / partners
  - What have we accomplished (listing the timeline and what has occurred)
  - Strategic Direction (where are we headed, what tasks are in the queue)

Also, if it wasn't clear above, I don't think that the actual pages need to change that much, I think this is more just adding a layer in between the TOC and the content.  I see a more user friendly TOC (friendly to those that aren't intimately familiar with the project history and context).  Then the new TOC links could take the user to new mid-point pages, which would then connect the user to the current pages / content.

An example the Active Work link on the TOC could take the user to a new annotated outline wiki page that guides the user to all the resources and pages related to active work, which would then bring the user to the current pages / content.  

For historic work, I think we would want to break up the current pages from the historic pages (like the minutes page we should have historic versus current (maybe at the bottom of current it could link to historic).  The minutes page should also have heading breaks of major phases / milestones in the work, which would relate to the annotated outline wiki page on Completed Work.

**Comment by joecastiglione** [comment]
I'm also supportive of a reorg of the project material within and across
activitysim.org and the wiki.  Joe and Alex can get this discussion going
(other interested partners should reach out to Joe to coordinate a separate
meeting time for partners to address these issues).  The goal would be to
come up with some explicit guidance about the purpose of activitysim.org vs
the purpose of the wiki.  This will help us channel material to one or the
other site, as appropriate.

I think the proposed reorg of TOC on the wiki sounds good.  Understood that
major changes to the content may not be required.    I'm open to
changing the references to phases, but I do think it is important that we
use consistent language for how we refer to the tranches of work.

**Comment by bstabler** [comment]
Some of this has been completed, see https://github.com/ActivitySim/activitysim/wiki

**Comment by bstabler** [comment]
I think we did this so I'm closing it
