### ISSUE TITLE
constants class

### ISSUE THREAD

**Issue by bstabler** [ActivitySim/activitysim#302]
We should probably move all these constants from the [constants class](https://github.com/ActivitySim/activitysim/blob/master/activitysim/abm/tables/constants.py) to the settings.yaml and then either drop the constants class completely and its usage and plumbing in the system, or update it so it wraps a CONSTANTS entry in the settings.yaml (similar to how model step CONSTANTS work).

**Comment by toliwaga** [comment]
yes! happy to wrap this into my current dev effort.

**Comment by toliwaga** [comment]
this is in multizone branch now - should close when we pull it to develop

**Comment by bstabler** [comment]
this was released, thanks
