### ISSUE TITLE
replace chunk size with a more intuitive parameter

### ISSUE THREAD

**Issue by albabnoor** [ActivitySim/activitysim#317]
from the user guide, "The chunk_size is the number of doubles in a chunk of the choosers table. It is approximately the number of rows times the number of columns and it needs to be set to a value that efficiently processes the table with the available RAM."

It'd be great if the user could specify the amount of available RAM and the software internally determines the chunk size. It is much more intuitive and easier for the user to specify.

**Comment by mattwigway** [comment]
This confused me too, as I initially assumed chunk_size was the number of individuals in a chunk, not the number of 64-bit numbers. To avoid breaking configs, maybe we should leave chunk_size as is, but add a chunk_size_megabytes parameter which, if chunk_size is not set, sets chunk size to chunk_size_megabytes * 1024 * 1024 / 8?

**Comment by bstabler** [comment]
#397
