### ISSUE TITLE
How difficult to run in a new city?

### ISSUE THREAD

**Issue by dabreegster** [ActivitySim/activitysim#326]
Hi,

I'm the developer of [A/B Street](https://github.com/dabreegster/abstreet/), a traffic simulator that lets the general public become more involved with influencing local transportation projects. The project needs people/activity/trip data as input; it currently uses Seattle's [Soundcast](https://github.com/psrc/soundcast) model, built on DaySim. Recently groups in other cities are interested in using A/B Street, but we're having trouble finding equivalent demand models.

@jvolker and @tori-d have tracked down some relevant input for [Berlin](https://github.com/dabreegster/abstreet/issues/119), such as travel surveys, census, and bike counters. How hard would it be for them to start using ActivitySim? Skimming through the [example](https://activitysim.github.io/activitysim/abmexample.html#inputs), I think we could actually generate most of the input from OpenStreetMap and the other Berlin sources.

I'd like to help more cities onboard to A/B Street, but I have absolutely no experience with travel demand modelling. Is there interest from ActivitySim in making a simple form of the modelling available to a large number of cities? If so, I'd love to find some sort of collaboration where you can use A/B Street to help visualize your output and debug individual people and trips. For instance, we've tools for exploring aggregate patterns:

![commute](https://user-images.githubusercontent.com/1664407/88429361-55c07780-cdab-11ea-9cdc-79dac66c3a5c.png)

Thanks,
-Dustin

**Comment by bstabler** [comment]
Hi @dabreegster.  The model requires detailed information on regional households, persons, and land use by zone (or neighborhood), and several detailed measures of network level-of-service by mode and time-of-day from zone to zone (or neighborhood to neighborhood).  An example of the required inputs is at: 
 https://github.com/RSGInc/activitysim_resources/tree/master/mtc_data_full.  

Let me talk with the rest of the team about your request and then reply again.  Thanks.

**Comment by dabreegster** [comment]
Thanks for the response! I dug through the examples a bit more, and I think some of this could be automatically generated from an OpenStreetMap extract and an American Commuter Survey. Of course the quality would suffer, but it could be useful as an initial low-effort seed for a new area. Would this be of value to any groups you work with?

By the way, is there any documentation on what some of the field acronyms mean? I found  [FPSEMPN](https://activitysim.github.io/activitysim/howitworks.html) mentioned here and in a few scripts, but can't figure out this one, or many others from `land_use.csv`.
