### ISSUE TITLE
Coefficients by Segment Necessary for Preprocessor

### ISSUE THREAD

**Issue by danielsclint** [ActivitySim/activitysim#333]
Should the coefficients line 96 be added to the local dictionary before the expressions are evaluated for the preprocessor_settings? In the ARC implementation, tour_mode_choice_annotate_choosers_preprocessor.csv, references coefficients defined in the tour_mode_choice_coeffs and tour_mode_choice_coeffs_templates. They would only be available if the coefficients were added to the local_dict before the expressions are evaluated in line 88.

https://github.com/ActivitySim/activitysim/blob/05a25f687e0c151c5a3bcbf4428d2b58dd2cc4f7/activitysim/abm/models/util/vectorize_tour_scheduling.py#L84-L98

**Comment by toliwaga** [comment]
Agreed. Will put this into develop asap.
