### ISSUE TITLE
Joint Tour Destination Changed to Use Non-Mandatory Destination Choice Model Settings

### ISSUE THREAD

**Issue by danielsclint** [ActivitySim/activitysim#335]
In PR #325, the model configuration file for joint tour destination was pointed to use the same model specification as non_mandatory_tour_destination. For consistency sake, would it be better to keep each model self-contained in its own YAML?

https://github.com/ActivitySim/activitysim/blob/05a25f687e0c151c5a3bcbf4428d2b58dd2cc4f7/activitysim/abm/models/joint_tour_destination.py#L329-L330

**Comment by toliwaga** [comment]
Yes - and especially as there is such a file, but it is currently ignored (and missing a field)

The only thing is that sometimes (e.g. for mtctm1) it will be identical to non_mandatory_tour_destination.yaml

it would be nice to have a macro (like inherit_settings) that allows you to say something like:

include_settings: non_mandatory_tour_destination.yaml

**Comment by danielsclint** [comment]
This was dealt with in PR #342.
