### ISSUE TITLE
Inherit Settings Macro

### ISSUE THREAD

**Issue by danielsclint** [ActivitySim/activitysim#348]
Related to #335...

@toliwaga said:

_Sometimes (e.g. for mtctm1) [two YAML specificiations] will be identical to non_mandatory_tour_destination.yaml it would be nice to have a macro (like inherit_settings) that allows you to say something like:_

```include_settings: non_mandatory_tour_destination.yaml```

**Comment by toliwaga** [comment]
this is too cool to resist!

**Comment by toliwaga** [comment]
It would probably be best to provide only a limited functionality for this. 

There is a lot of opportunity for confusion if this feature were over-used (e.g. endless chains of include files that reference each other...) when all we really need (for now) is to support an include that makes the setting file an alias for anther settings file.

Maybe we insist that a file with an include directive is the 'end of the road' and can't contain or inherit other settings?

**Comment by joecastiglione** [comment]
Supportive of convenience, but I think we also want to ensure that
specifications are transparent and clear / legible.

**Comment by bstabler** [comment]
#397
