### ISSUE TITLE
Hard Coded Person Types in CDAP

### ISSUE THREAD

**Issue by danielsclint** [ActivitySim/activitysim#356]
The CDAP model contains hard coded person type (ptype) values for workers and children.

For the ARC implementation this causes problems in the tour scheduling components where the children ptypes are further subdivided beyond the values in the hard-coded expression. We would ideally like to be able to define 9 as another child person type for tour scheduling, but this would break the upstream CDAP components.

Preferably, the ptypes should be asserted in the settings.yaml or one of the model configuration yaml files.

https://github.com/ActivitySim/activitysim/blob/964ee009f81f2fe14e908ed8a3f1881f04d07127/activitysim/abm/models/util/cdap.py#L38-L39

**Comment by bstabler** [comment]
These should move to the new constants.yaml file

https://github.com/ActivitySim/activitysim/blob/multizone/activitysim/examples/example_mtc/configs/constants.yaml

**Comment by danielsclint** [comment]
This feature is not available on the develop branch at this point in time, so I didn't incorporate it. I did just issue a pull request to address the ARC specific issue this issue relates.

**Comment by bstabler** [comment]
this is in the release version now
