### ISSUE TITLE
Time Map Should Allow Labels to Be Reused

### ISSUE THREAD

**Issue by danielsclint** [ActivitySim/activitysim#358]
In the settings.yaml, the skim_time_periods should allow for duplicate labels. In the MTC / ARC example, the EV period would cover the first few hours in the early morning after midnight and the late night shortly before midnight.

It's also easy to imagine a model with 2-3 time periods like Peak / Off-Peak, or AM, PM, OP.

**Comment by bstabler** [comment]
this is in the release, thanks
