### ISSUE TITLE
Further Reduce Logsum Calcs in Mandatory Tour Scheduling

### ISSUE THREAD

**Issue by danielsclint** [ActivitySim/activitysim#361]
ActivitySim already reduces down the number of logsum calculations by filtering out some duplicate value. However, in the ARC ActivitySim implementation, we have a lot of duplicated logsum calculations. Could this be refined to filter and remove extraneous rows just on just in_period and out_period?

I don't think duration is relavent to the actual logsum calculation, and the log sum calculation could be re-expanded to deal with the durations. In the ARC example, this would reduce the number of logsum calculations by an order of magnitude.

https://github.com/ActivitySim/activitysim/blob/df28db708d672ed8b13d5119fffc867bc24121bf/activitysim/abm/models/util/vectorize_tour_scheduling.py#L145-L150

**Comment by bstabler** [comment]
This is a good idea.  In addition, while still keeping logsum calcs by [origin, destination, duration], we could de-duplicate the alternatives since some [origin, destination, duration] tuples could result in the same values as well.

**Comment by toliwaga** [comment]
While the ARC version does not use duration, it is used by MTC to calculate daily_parking_cost:

`,daily_parking_cost,"np.where(is_mandatory, _hourly_peak_parking_cost * df.duration, _hourly_offpeak_parking_cost * df.duration)"`

But I believe we have addressed this issue with representative_logsums performance enhancement feature now in develop2...

**Comment by bstabler** [comment]
#417
