### ISSUE TITLE
ask a woman to commit some code to this repository

### ISSUE THREAD

**Issue by Ennazus** [ActivitySim/activitysim#379]
Bad optics. Let me know how I can help. I was just checking things out because I saw a bunch of PSRC code updates which is cool!  I'm excited to see what you pull together. Do you want me to write a summary tool or something? I can volunteer a few hours.

I'm also available for model estimation or model design assistance. We've been estimating a bunch of models lately that include race https://github.com/psrc/travel-studies/blob/master/2019/analysis/zero_veh_hh/Veh_model_02022021.Rmd, and we've been looking into telecommuting https://github.com/psrc/data-science/blob/master/HHSurvey/telecommuting/telecommute_model.R and home deliveries.https://github.com/psrc/data-science/blob/master/HHSurvey/delivery_model_upd.R

@stefancoe @bstabler

**Comment by e-lo** [comment]
was this resolved?

**Comment by Ennazus** [comment]
I meant this as a playful nudge to get a more diverse contributor base, but then I felt like it was probably not the best way to get the issue across. Also I’m guessing that the issue has been successfully raised!

**Comment by josiekre** [comment]
+1 on the nudge. Great idea! Someone else sent me to this so it is being noticed!
