### ISSUE TITLE
add estimation examples for remaining submodels

### ISSUE THREAD

**Issue by bstabler** [ActivitySim/activitysim#382]
@jpn-- is working on this, as well as general improvements for more seamless estimation integration

**Comment by jpn--** [comment]
## implement components

- [x] free_parking
- [x] mandatory_tour_frequency
- [x] mandatory_tour_scheduling
- [x] joint_tour_frequency
- [x] joint_tour_composition
- [x] joint_tour_participation
- [x] joint_tour_destination (with nonmandatory tour destination)
- [x] joint_tour_scheduling
- [x] non_mandatory_tour_destination
- [x] non_mandatory_tour_scheduling
- [x] atwork_subtour_frequency
- [x] atwork_subtour_destination
- [x] atwork_subtour_scheduling
- [x] atwork_subtour_mode_choice (with tour mode choice)
- [x] stop_frequency
- [x] trip_destination
- [x] trip_mode_choice

## required testing

- [ ] more rigorous testing for the presence of "include_settings" and "inherit_settings" situations

## notebooks
- [x] truly simple simple_simulate (free parking, auto_ownership, ...)
- [x] composite simple_simulate (trip mode choice, stop frequency)
- [x] multiple composite simple_simulate (tour and subtour mode choice)
- [x] simple location choice (work location, school location)
- [x] multiple location choice components (joint & non-mandatory destination choice)
- [x] cdap
- [x] non_mandatory_tour_frequency

**Comment by bstabler** [comment]
#417
