### ISSUE TITLE
continue to improve our test system to cover activitysim use cases in practice 

### ISSUE THREAD

**Issue by bstabler** [ActivitySim/activitysim#385]
See the [task scope](https://github.com/ActivitySim/activitysim/wiki/Phase-6a-Scope-of-Work#task-6-prototype-multiple-models-test-system) for the general idea.  See also the evolving [examples](https://github.com/ActivitySim/activitysim/tree/develop2/activitysim/examples) set and [example_manifest](https://github.com/ActivitySim/activitysim/blob/develop2/activitysim/examples/example_manifest.yaml).

**Comment by bstabler** [comment]
Proposed improvement plan will be [here](https://github.com/ActivitySim/activitysim/wiki/Improved-test-system-to-cover-activitysim-use-cases)

**Comment by bettinardi** [comment]
the "here" link doesn't work

**Comment by bstabler** [comment]
#417
