### ISSUE TITLE
On develop2 branch, assertion error in skim_dictionary.py, los.py

### ISSUE THREAD

**Issue by stefancoe** [ActivitySim/activitysim#387]
When we run with full PSRC data, [line 69 in skim_dictonary.py](https://github.com/ActivitySim/activitysim/blob/develop2/activitysim/core/skim_dictionary.py#L69) fails because offset_series is a numpy array not a series. 

To move along, I changed [this line](https://github.com/ActivitySim/activitysim/blob/develop2/activitysim/core/skim_dictionary.py#L50) to:
            
self.set_offset_series(pd.Series(offset_series))

However, there is another issue [on line 337 in los.py](https://github.com/ActivitySim/activitysim/blob/develop2/activitysim/core/los.py#L337) where I think skim_dictionary has treated our skims as having a default offset of -1, which is reflected in self.skim_dicts['maz'].zone_ids (min 0, max 51187) but not in self.maz_taz_df['MAZ'].values (min 1, max 66234). I suspect that the psrc_example data is working because the first MAZ/TAZ is 47, 347 so the code constructs a non-default offset mapper and presumably this code is working?

**Comment by stefancoe** [comment]
I tested the code using the psrc_example data and can confirm that the example data uses the following in [skim_dictionary.py](https://github.com/ActivitySim/activitysim/blob/develop2/activitysim/core/skim_dictionary.py#L179):

offset_mapper.set_offset_list(offset_list=self.skim_info.offset_map)

Whereas the full psrc data uses:

offset_mapper.set_offset_int(-1)

**Comment by toliwaga** [comment]
Thanks @stefancoe  There was indeed a bug that was only triggered when the taz skims backing a MazSkimDict had no offset map. I, unfortunately, missed this as I had been running your full example, not on the raw data you provided me, but on a  version created by the psrc_crop.py script in the example_psrc/scripts folder which removes unreferenced TAZs from the skims and uses omx.create_mapping to add a mapping – thus hiding the bug from me when I ran your full example.

**Comment by bstabler** [comment]
This is fixed on develop2 so I'm going to close this
