### ISSUE TITLE
Skim Dictionary Lookup Fails in Estimation Mode

### ISSUE THREAD

**Issue by bricegnichols** [ActivitySim/activitysim#388]
When checking for bad indices, the following assertion fails when reading survey data that contains -1 values:

https://github.com/ActivitySim/activitysim/blob/master/activitysim/core/skim_dictionary.py#L244

I don't really understand the implications, but I bypassed the issue by allowing -1 as a valid value:

```
in_skim = (mapped_orig >= -1) & (mapped_orig < self.omx_shape[0]) & \
                  (mapped_dest >= -1) & (mapped_dest < self.omx_shape[1])
```

**Comment by bricegnichols** [comment]
This issue occurred on the develop2 branch running PSRC's MAZ-based model.

**Comment by bstabler** [comment]
@bricegnichols - can you provide more info and then @toliwaga and you can plan to chat if needed

**Comment by jfdman** [comment]
@bricegnichols can this issue be closed?

**Comment by bricegnichols** [comment]
I haven't checked to see if it was ever resolved, so we can close it for now and revisit later if needed.
