### ISSUE TITLE
set MKL_NUM_THREADS=1 at runtime?

### ISSUE THREAD

**Issue by bstabler** [ActivitySim/activitysim#414]
Inspired by [this](https://numexpr.readthedocs.io/projects/NumExpr3/en/latest/user_guide.html#threadpool-configuration), should we add something like the following to the asim main runner to ensure we always override the Intel MKL threading settings on Windows and when multiprocessing?  

```
import os
os.environ['MKL_NUM_THREADS'] = '1'
```

**Comment by bstabler** [comment]
@guyrousseau asked if the Intel MKL library underlying numpy and pandas work as well on AMD processors.  Based on [this](https://en.wikipedia.org/wiki/Math_Kernel_Library) Wikipedia entry and some [other web searching](https://simon-martin.net/2020/03/01/boosting-intel-mkl-on-amd-ryzen-processors/), it may not.  However, this information may be out of date as Intel, AMD, numpy/pandas, etc. are always making improvements.

**Comment by jpn--** [comment]
If we want to squash threads not just for MKL but other BLAS implementations that a use may end up with (and many other of the usual suspects), we can do the same ='1' for all these:  OMP_NUM_THREADS, NUMBA_NUM_THREADS, OPENBLAS_NUM_THREADS, MKL_NUM_THREADS, VECLIB_MAXIMUM_THREADS, NUMEXPR_NUM_THREADS.  We'd need to make sure we don't accidentally squash anything we need, but at first glance squashing all these threads probably won't ruin anything.

Alternatively, we can look at [threadpoolctl](https://github.com/joblib/threadpoolctl) for less heavy-handed runtime control.

**Comment by guyrousseau** [comment]
ARC completely agrees with the recommendation.  Setting the maximum number of threads to align with the number of available processors will reduce overhead.  While it is possible to create more threads than available processors, and at times this can be useful, there is no benefit to doing so when you have a distributed computational platform such as the ActivitySim ABM.   A higher thread count could actually create CPU contention, which is then reliant on the internal CPU scheduler to ensure all threads are processed before accepting new inputs, thus slowing down the system during high computation events.
