### ISSUE TITLE
Missing larch model "component_model"

### ISSUE THREAD

**Issue by bricegnichols** [ActivitySim/activitysim#415]
I think that the larch package release may need to be updated to work with the latest changes on activitysim. From the example_estimation notebook, when the line `from activitysim.estimation.larch import component_model` is run the following error is returned: 

```
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-4-daaf04899a35> in <module>
----> 1 from activitysim.estimation.larch import component_model
      2 model, data = component_model(modelname, return_data=True)

c:\users\modeller\workspace\activitysim\activitysim\estimation\larch\__init__.py in <module>
      1 import larch
      2 
----> 3 from .cdap import *
      4 from .data_maker import *
      5 from .general import *

c:\users\modeller\workspace\activitysim\activitysim\estimation\larch\cdap.py in <module>
      4 import itertools
      5 from larch import P, X, DataFrames, Model
----> 6 from larch.model.model_group import ModelGroup
      7 from larch.util import Dict
      8 import larch

ModuleNotFoundError: No module named 'larch.model.model_group'
```

I am running activitysim from the develop branch using `setup.py develop` and installed larch with `conda install larch -c conda-forge`

This was not a problem for the initial merge of Pull Request #400

**Comment by jpn--** [comment]
Can you check what version of larch was installed?  From within Python:

```
>>> import larch; larch.__version__
'5.5.2'
```

or at the anaconda prompt:

```
(asim-dev) C:\Users\jeffnewman>conda list | grep larch
larch                     5.5.2            py39h5d4886f_0    conda-forge
```

I am not sure why, but anaconda has been installing older versions of larch from conda-forge sometimes.  If you've got an old one, try upgrading:

```
(asim-dev) C:\Users\jeffnewman>conda install "larch>=5.5.2" -c conda-forge
```

**Comment by bricegnichols** [comment]
Thanks, Jeff, that was the issue. Seems to be running fine now.

**Comment by jpn--** [comment]
Also: it's possible the current version of Larch on conda-forge is somehow broken, I just discovered there was some sort of [infrastructure failure](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=298658&view=results) on Azure during the most recent build. I'm going to try to re-build it.  If you're showing Larch 5.5.2 or later and still getting an error, wait a few hours and try again.

**Comment by jpn--** [comment]
Super!
