### ISSUE TITLE
 problem with skim names in create example_xxx_full

### ISSUE THREAD

**Issue by toliwaga** [ActivitySim/activitysim#421]
activitysim create example_xxx_full are broken where skims are split due to size. (i.e. where there are skims1.omx, skims2.omx,...)

This is because the manifest copies the example data folder then adds the skims to it, but if the example folder has a skims.omx for the small dataset, it doesn't get overridden and then the taz_skims specifier glob (in network_los.yaml) matches the residual file (which is the wrong size) in addition to the skims<n>.omx files and activitysim flags this as an error (which it indeed is.)

```
# this line in network_los.yaml causes problems 
taz_skims: taz_skims*.omx
```

**Comment by toliwaga** [comment]
Additionally, example_sandag_full refer has four files misnamed in the full data causing similar problems

maz_maz_walk.csv  <- destination incorrectly named and so fails to overwrite maz_to_maz_walk.csv

(but I fixed this latter issue in rss_chunk branch which will soon be merged to develop)

**Comment by bstabler** [comment]
thanks @toliwaga, I tried to tidy up all the examples but missed a couple of items.  I simply deleted the small dataset skims.omx but now I'm wondering if it would be better to rename the small dataset skims.omx to skims1.omx so we can reuse the settings files.

**Comment by jpn--** [comment]
If renaming stuff, please make them with useful descriptive names, like "skims_small1.omx" or "skims_full1.omx" so it's obvious which files go with which tests.
