### ISSUE TITLE
Convert distribution system to conda-forge

### ISSUE THREAD

**Issue by jpn--** [ActivitySim/activitysim#424]
The "estimation mode" test is travis is encountering sporadic failures in setting up the environment.  The actual ActivitySim code appears healthy, it's just the install of the conda test environment that is encountering a timeout.  Revising the test install process to use conda-forge from the start and to avoid flopping between the conda-forge and default channels (larch is not available in the default channel) may make this more stable.

**Comment by bstabler** [comment]
Everything is ready to go on our end.  We're just now waiting for conda forge to compile the recipe.  Stay tuned.

**Comment by jpn--** [comment]
The logjam is cleared, and version 1.0.2 is now on conda-forge.  https://anaconda.org/conda-forge/activitysim
