### ISSUE TITLE
Long walk and bike distance trips

### ISSUE THREAD

**Issue by esanchez01** [ActivitySim/activitysim#432]
While summarizing the SANDAG 3 Zone example outputs, we noticed that a small portion of the walk and bike trips exceeded their 3 and 8 miles limits, respectively. Since the SANDAG example relies heavily on the MTC example's configuration files, we ran the MTC example to see if the same issue existed, and it did. After investigating, the issue seems to be due to the following two expressions in [trip_mode_choice.csv](https://github.com/ActivitySim/activitysim/blob/a57efa1418320cb88d72ad5f413aaa45131183a4/activitysim/examples/example_mtc/configs/trip_mode_choice.csv#L401):

Label | Description | Expression | WALK | BIKE
-- | -- | -- | -- | -- |
util_Walk_not_available_for_long_distances | Walk not available for long distances | @df.tour_mode_is_walk &amp; (od_skims['DISTWALK'] &gt; 3) | -999
util_Bike_not_available_for_long_distances | Bike not available for long distances | @df.tour_mode_is_walk &amp; (od_skims['DISTBIKE'] &gt; 8) |  | -999

Although the distance limits are specified, they are only applied when the tour mode is walk (should instead be 'df.tour_mode_is_bike' for the bike expression?). Is this the intended behavior? If, for example, the tour mode for a trip is Drive Alone, it would be possible for a 'long' distance intermediate trip to be set as Walk as the expression does not cover this case.

After rerunning the MTC example with the revised expressions below, the maximum walk and bike distances were at or under their limits.

Label | Description | Expression | WALK | BIKE
-- | -- | -- | -- | -- |
util_Walk_not_available_for_long_distances | Walk not available for long distances | @od_skims['DISTWALK'] &gt; 3 | -999
util_Bike_not_available_for_long_distances | Bike not available for long distances | @od_skims['DISTBIKE'] &gt; 8 |  | -999

**Comment by jpn--** [comment]
@bstabler, this looks like maybe a technical error that came up in the MTC model that RSG built earlier, want to take a look?

**Comment by bstabler** [comment]
I checked the travel model one UECs ([tour mode choice](https://github.com/BayAreaMetro/travel-model-one/blob/master/model-files/model/ModeChoice.xls) and [trip mode choice](https://github.com/BayAreaMetro/travel-model-one/blob/master/model-files/model/TripModeChoice.xls)) and the ActivitySim setup is consistent.  As a result, I'm hesitant to revise the example.
