### ISSUE TITLE
Shadow Pricing Size Term Results Missing

### ISSUE THREAD

**Issue by danielsclint** [ActivitySim/activitysim#433]
When I run the ARC example with Shadow Pricing (`use_shadow_pricing: True`), no shadow price results seem to be exported from the model. I see trace files from each iteration.

Also, is there an example of how to specify the shadow prices as an input into the model, so we don't need to run shadow_pricing every model run?

**Comment by bstabler** [comment]
@danielsclint to investigate, thanks Clint

**Comment by danielsclint** [comment]
### Warm Start Shadow Pricing
The code does have a spot where shadow prices are [read into the model](https://github.com/ActivitySim/activitysim/blob/a57efa1418320cb88d72ad5f413aaa45131183a4/activitysim/abm/tables/shadow_pricing.py#L169-197). Within the model specification YAML (e.g., school location, work location), the user needs to specify a property called `SAVED_SHADOW_PRICE_TABLE_NAME`. These shadow prices appear to read from the `data` folder by default. The ActivitySim documentation does not include any references to this parameter nor does it include any information about the format of this table.

### Saving Shadow Prices
At the end of each shadow pricing iteration, ActivitySim safes shadow prices to the output as ["trace files"](https://github.com/ActivitySim/activitysim/blob/a57efa1418320cb88d72ad5f413aaa45131183a4/activitysim/abm/tables/shadow_pricing.py#L549). Its not super clear this is what is actually happening from the end user perspective based on file naming conventions

Suggested Fix:

1. Add documentation for the `SAVED_SHADOW_PRICE_TABLE_NAME`. @bstabler: The question here is where should the documentation be updated. TBH, it would be nice if the documentation included a descriptor of each of the model specification files.

2. Add documentation to the same location as above indicating that the "trace" files are, in fact, the warm start tables. @bstabler: Again, where in the documentation should this go.

**Comment by bstabler** [comment]
I think we should add more documentation for shadow pricing [here]( https://github.com/ActivitySim/activitysim/blob/master/docs/models.rst#shadow-pricing).  This section is largely built from the code docstrings, but it looks like the [ShadowPriceCalculator](https://github.com/ActivitySim/activitysim/blob/master/activitysim/abm/tables/shadow_pricing.py#L79) docstrings are not included so much of the documentation didn't make it onto to the webpage.  I assume you can make the doc updates, but if you need help, just let me know.  Thanks.

**Comment by danielsclint** [comment]
I added a more lay man's set of documentation to the RST files.

https://github.com/ActivitySim/activitysim/pull/480

**Comment by bstabler** [comment]
this was completed under #480
