### ISSUE TITLE
make orca an official dependency

### ISSUE THREAD

**Issue by bstabler** [ActivitySim/activitysim#437]
Moving forward let's make the BSD-3 licensed [orca](https://github.com/UDST/orca) an official dependency

**Comment by bstabler** [comment]
I think @jpn-- is going to do this?

**Comment by jpn--** [comment]
A few seconds looking at the commit referenced above, it appears that @toliwaga maybe actually did most of this already; orca.py's gone from the repo now.  I'll check more carefully soon and make sure our dependencies are installing correctly and everything, but my guess is it's good as travis is still passing.

**Comment by jpn--** [comment]
on further review, it looks like orca came back in 5a52dda147a21c4f80e93c40f5adf122f5dde193, probably unintentionally.  I'll cut it out again.

**Comment by toliwaga** [comment]
Not unintentionally. If orca is in the environment, it is used, otherwise
core/orca.oh is used.

If you remove core/orca you should also remove the code (in inject amd
pipeline) that supports the two options.

**Comment by toliwaga** [comment]
Sorry - I meant to say:

If orca is in the environment, it is used, otherwise core/orca.py is used.

**Comment by bstabler** [comment]
this is in #455
