### ISSUE TITLE
GitHub Permissions for WSP Team

### ISSUE THREAD

**Issue by danielsclint** [ActivitySim/activitysim#441]
The following users need privileges in GitHub for Phase 6B.

- @danielsclint (Clint Daniels): Appropriate permissions to address and merge Pull Request and assign issues
- @billyc (Billy Charlton): Appropriate permissions to update Wiki / potentially merge pull request  and assign issues
- @e-lo (Elizabeth Sall): Appropriate permissions to address and merge Pull Request and assign issues
- @ddorinson (Diana Dorinson): Appropriate permissions to update Wiki

At this point in time, the rest of the WSP contributors will issue PR to the ActivitySim repo.

**Comment by bstabler** [comment]
I granted everyone write access.  Thanks.
