### ISSUE TITLE
Visualization

### ISSUE THREAD

**Issue by bstabler** [ActivitySim/activitysim#443]
@danielsclint - We're now creating tasks for work moving forward so I created this placeholder task for your [visualization task](https://github.com/ActivitySim/activitysim/wiki/Phase-6b-Scope-of-Work#task-4-visualization).  Feel free to use this task, create tasks for subtasks, or manage it how you see fit using Issues so folks can follow along.  Thanks.

**Comment by billyc** [comment]
@bstabler  Could you create a new Milestone for **Phase 6b Task 4: Visualization** please? I don't have the right permissions. 

Thanks!

**Comment by bstabler** [comment]
@billyc done

**Comment by bstabler** [comment]
see work being done at https://github.com/ActivitySim/dashboard

**Comment by dhensle** [comment]
See [visualization product document](https://docs.google.com/document/d/18MCr2m48b6n_bMaxKeicBQ7HQ_3AZ_4QkhAG6fqBavc) for details
