### ISSUE TITLE
Max Time Block Available vs Remaining Periods Available

### ISSUE THREAD

**Issue by danielsclint** [ActivitySim/activitysim#450]
At some point earlier this year, a new method was added (max_time_block_available) obstensibly to support the SEMCOG implementation. This is great, but the check-in did not follow the commit protocol questionaire referenced in the documentation. We now have two method, max_time_block_available and remaining_periods_available, that appear to do two very similar things. 

I think the max_time_block_available is the change that @jfdman implied was a missing method in the original specification of time windows for ActivitySim. It looks like, however, that it largely replaced remaining_periods_available in the SEMCOG model, but it wasn't updated in any other examples. 

Does this new method make the old one obsolete, and should we all be updated our implementations to use the new method?

https://github.com/ActivitySim/activitysim/blob/5803923238856a4be95a27a778f2478225484b8c/activitysim/core/timetable.py#L640

https://github.com/ActivitySim/activitysim/blob/5803923238856a4be95a27a778f2478225484b8c/activitysim/core/timetable.py#L601

**Comment by bstabler** [comment]
We kept ``remaining_periods_available`` for backwards compatibility.  We're going to check which examples use it and why.  We may be able to drop it now that we have ``max_time_block_available``.

**Comment by danielsclint** [comment]
It looks like the `remaining_periods_available` is being used across a number of implementations. 

This is from @jfdman in an email on 2/9/2021 (@bstabler was on the cc):

> 10.	Time pressure calculation is not correct in this expression and others like it. The time pressure variable for ARC is supposed to be calculated as the maximum number of contiguous time periods available divided by the number of tours left to schedule. But the ActivitySim code does not currently have a method to calculate maximum number of contiguous periods available. The UEC is calculating it as number of periods available during the time period of the alternative, which is not right. Jeff Doyle is going to implement the required method shortly.
https://github.com/wsp-sag/client_arc_activitysim/blob/master/configs/tour_scheduling_nonmandatory.csv#L94 

What is not clear to me is whether the new `max_time_block_available` was inserted to address this problem. At the end of @jdfman's message above, he said that @toliwaga "is going to implement the required method shortly". Is this the required method?

If so, does that also mean that the other examples need to be updated and the "old" method deprecated? I would think that the ARC and MTC examples would be very similar in their UEC implementations since they were jointly developed.

**Comment by bstabler** [comment]
Yes, this is the new method, and its use is illustrated [here](https://github.com/ActivitySim/activitysim/blob/master/activitysim/examples/example_semcog/configs/tour_scheduling_nonmandatory_shopping.csv).  Let me look into the deprecation question some more.

**Comment by danielsclint** [comment]
I found the reference between the ARC UEC and the `max_time_block_available`. The UEC referenced a method called [`getTimePressure`](https://github.com/wsp-sag/arc/blob/0a8a8583efadca06c48fc98673977c006bb170dc/src/java/com/pb/arc/tourBased/ArcTourDepartureTimeAndDurationDMU.java#L189). The `getTimePressure` then references [`getMaxTimeBlockAvailable`](https://github.com/wsp-sag/ctramp/blob/9b0c42f4f38a631d05d087ca888462d4ba400ab9/src/java/com/pb/models/ctramp/Person.java#L307) on the generic Person object in the core CT-RAMP code. The ActivitySim code replicates this method.

I don't see a similar method in the [MTC TM1 TourDepartureAndDuration UEC](https://github.com/BayAreaMetro/travel-model-one/blob/master/model-files/model/TourDepartureAndDuration.xls). I'm guessing `max_time_block_available` was introduced with the ARC model, and it does carry over to the SANDAG model.

I'm going to close this ticket, and I'll update the ARC model.
