### ISSUE TITLE
Travis Python versions

### ISSUE THREAD

**Issue by jpn--** [ActivitySim/activitysim#451]
We currently test in Travis against Python versions 3.7 and 3.8.  The current "latest" version is 3.9, which was released in October 2020.  It's now mature and all our dependencies are available on Python 3.9. 

(a) I suggest we begin testing and supporting Python 3.9.  Doing so will also help with automating PYPI release deployment via travis, as travis can only deploy what it tests.  This should be uncontroversial.

(b) The current full suite of tests takes 4 hours to run on travis.  If we add 3.9 and don't drop 3.7, that will increase the testing time to 6 hours.   In the long run once agency production models are in use we probably won't want to drop support for older Pythons until the PSF drops them (for 3.7 that will be June 2023).   But given that no one is yet maintaining a legacy production ActivitySim model, an argument can be made that we can (any maybe should) drop support for Python 3.7 now, just to keep a lid on the number of different versions we need to maintain. 

(c) Should we push that theory to the limit and require Python 3.9 or better starting now?

**Comment by bstabler** [comment]
(a) agreed
(b) agreed
(c) fine by me, but I wonder if others have an opinion?

**Comment by bstabler** [comment]
We agreed on the 7/15 call to require the current python release, so 3.9 for the time being.  If an agency model is in production and uses an older version, then we may support it for some time as well.  Agencies can always freeze the version of asim they are using.  We plan to discuss this topic some more as agency use increases.

**Comment by bettinardi** [comment]
Just to put a quick vote in - 
ODOT would be freezing any production version of ActivitySim.  Once we have a calibrated ActivitySim used with an adopted RTP, we would be refraining from doing any software updates to that copy.  JPN mentioned a bug issue, and if a really big bug were found we would have to unfreeze and figure that out.  But TDM's have minor bugs, that's just a fact.  So we would have a new version probably in the works while we have a production version frozen.  In summary, my vote / push would be that users should be freezing copies as they go into production (live application) and that the code base should continue forward.  We do need to think about backwards compatibility and not totally ignoring that, but I don't think that means ensuring that ActivitySim is backwards compatible for everyone's frozen copy.   - Just adding my two cents (https://en.wikipedia.org/wiki/My_two_cents)

**Comment by bstabler** [comment]
in #455
