### ISSUE TITLE
Failure in choose_intermediate_trip_purpose() funtion in trip_purpose model

### ISSUE THREAD

**Issue by stevenhz** [ActivitySim/activitysim#466]
Hi,

When running my own dataset, I encountered a failure at `choose_intermediate_trip_purpose` in trip_purpose.py file.  This is due to `if chooser_probs.sum() < num_trips:` is true. Indeed, in the trips dataframe there are trips having `primary_purpose` school while the person's person_type is `PTYPE_UNIVERSITY`, so there are no match records in `probs_spec` (which is from `trip_purpose_probs.csv`). 
![image](https://user-images.githubusercontent.com/15105936/127752119-3309af86-15ff-4ea2-a06c-c928f6f20179.png)

I saw in mandatory_scheduling.py line 55 mentioned primary_purpose, but the added column is "mandatory_tour_seg". Then I found in stop_frequency.py line 90 `trips['primary_purpose'] = reindex(tours.primary_purpose, trips.tour_id)`, but it comes from tours' primary purpose. 

Shall I ask where the `primary_purpose` is determined? How can I fix this data issue? 

Thanks!

kind regards,
Han

**Comment by bstabler** [comment]
https://github.com/ActivitySim/activitysim/blob/master/activitysim/examples/example_mtc/configs/stop_frequency_annotate_tours_preprocessor.csv#L3
