### ISSUE TITLE
Regenerate personal access token for ActivitySim push gh-pages

### ISSUE THREAD

**Issue by bstabler** [ActivitySim/activitysim#469]
From GitHub:

We noticed your personal access token, ActivitySim push gh-pages, has an outdated format...We recently updated the format of our API authentication tokens, providing additional security benefits to all our customers....In order to benefit from this new format, please regenerate your personal access token...To understand more about this change and why it's important, visit https://github.blog/2021-04-05-behind-githubs-new-authentication-token-formats.

**Comment by bettinardi** [comment]
Does this require an action from all partners?

**Comment by bstabler** [comment]
No, I can do it.  I just don't want to forget about it.
