### ISSUE TITLE
add improvements for SANDAG cross border model 

### ISSUE THREAD

**Issue by bstabler** [ActivitySim/activitysim#484]
See work being done in PR [#481](https://github.com/ActivitySim/activitysim/pull/481)

**Comment by wusun2** [comment]
SANDAG migrated its Crossborder model from CT-RAMP to ActivitySim recently.  The goals are: 1) better software engineering to improve model maintenance and performance 2) test ActivitySim extensibility on a special market model 3) update the model to reflect a recent survey.   The first two software engineering goals have been achieved.   Not only ActivitySim has been extended to a special market model, but also the ActivitySim-based software is 50-60% faster than the CT-RAMP software. Additionally, the results from ActivitySim-based software have been validated against the results from CT-RAMP. 

This PR only includes generic modules that potentially could benefit the core ActivitySim; it has no regional or Crossborder model specific features.  Care was taken to ensure all changes submitted are fully backward compatible with existing ActivitySim implementations.  Many special market models in the pipeline, such as the visitor model and the air passenger model,  likely will not operate on a synthetic population as in the core ActivitySim, rather they are more likely start with enumerating and constructing  trips.  The crossborder model could provide useful insights for other special market models in the pipeline.  SANDAG and RSG ask the consortium and the bench consultants to review this PR.

**Comment by bstabler** [comment]
We discussed on the 10/7 call that this task will remain open until the PR is accepted

**Comment by bstabler** [comment]
this has been merged so I'm closing the issue
