### ISSUE TITLE
chunk training takes time

### ISSUE THREAD

**Issue by stevenhz** [ActivitySim/activitysim#487]
Hi, 

In the latest version (1.0.3), I notice that when chunk_training_mode is training, the calculation time will be about 5x slower on a test dataset having 5000 households. Even I changed the mode to "production", it will turn automatically back to training because of lacking training information.

Although the training only needs once, for a simulation that takes 14 hours on an older version (0.9.7) with more than 1 million households, it may take a lot of time. Since I already had a reasonable chunk size. I was wondering if I can force activitysim to run in production mode?

Thanks a lot!

**Comment by bstabler** [comment]
Take a look at the [chunking documentation](https://activitysim.github.io/activitysim/core.html#chunk-size) for more information.  The previous version used one chunk size value for all submodels, where as the new version uses a separate value for each submodel.  I think what you'll need to do is first train the chunker and then run it in production mode.  You can use a sample of households to speed up the chunk training time.

**Comment by stevenhz** [comment]
Thank you!
