### ISSUE TITLE
intermediate stop location choice model calculations are incorrect for stops on the inbound leg of a tour

### ISSUE THREAD

**Issue by bstabler** [ActivitySim/activitysim#491]
from @jfdman.  We suspect the intermediate stop location choice model calculations are incorrect for stops on the inbound leg of a tour.  The way it should work is that for each sampled stop, there are two distance/logsum components. One from the last known location to the sampled stop location, and another from the sampled stop location to the next known location. For outbound stops, the last known location is either the tour origin (anchor location) – for the first stop, or the location of the last stop (for stops after the first stop). And the next known location is the tour primary destination.  For the next stop, the origin becomes the last stop location, and the destination is the primary destination still.  For outbound legs, it looks like the skim and logsum indexing is working correctly; the trip origin is being set to the last known location and the destination is being set to the primary destination. But for inbound legs, the next known destination should be the tour origin (aka anchor location) and subsequent stops.

**Comment by bstabler** [comment]
The fix committed above consists of two parts:

  - add a new column in the preprocessor called `tour_leg_dest`, which evaluates to the tour destination for outbound trips or the tour origin for inbound trips.
  - set the definition of the `primary_dest` skim lookup setting in the model yaml config to this new column.

This changes the `p` in the skims `dp` lookup to tour dest or tour origin depending on the trip direction.  In this way, we are able to cover all four of the lookup scenarios with only two sets of skim wrappers.

We should fix any other examples with this error as well, such as example_arc, example_psrc, and example_semcog.

**Comment by jfdman** [comment]
Did the bug also affect mode choice logsum calculations for the stop->origin leg on inbound stops? If so this code also needs to be fixed. Please also confirm that the time periods used in these calculations are correct (departure period for outbound stops, arrival period for inbound stops).

**Comment by bstabler** [comment]
It did, but the fix works for the logsums too.  The code to setup the logsums request is inside trip destination.  The time periods for the lookup are set in the trips preprocessor based on tour.start or tour.end depending on trip.inbound.

**Comment by bstabler** [comment]
I'll fix the examples before we release
