### ISSUE TITLE
work/school location choice

### ISSUE THREAD

**Issue by stevenhz** [ActivitySim/activitysim#514]
Dear Sir,

I have 2 questions regarding the school/work location choice: in my simulation, It turns out that the number of work tours is about 2x of the number of school tours. 

1.  Is this because in the land use data, the number of employees is about 2x of the number of students (primary school, high school, university)? 
2. Suppose the destination choice estimation causes an overestimating of the number of work tours,  the shadow pricing is disabled. Is it possible to reduce the number of work tours or increase number of school tours by changing location choice related parameters? 

Thank you for help!

**Comment by dhensle** [comment]
@joecastiglione do you want to reply to this?

**Comment by joecastiglione** [comment]
Re: Q1, If the number of workers in your synthetic population is roughly double the number of students, then yes this is the most likely explanation, as most workers on average make just under 1 work tour per day, and most students on average make just under 1 school tour per day.

Re: Q2, To clarify, is the issue that the number of work tours destined to a particular TAZ or TTAZs is overestimated relative to the employment in that TAZ (which certainly could be destination choice issue related to disabled shadow pricing), or that the number of work tours overall is too great (which would be a tour frequency issue)?  It is obviously possible change the location choice models' parameters / specifications, but I would strongly discourage you from doing so, absent the availability of a travel diary survey from which you have estimated new parameters based on observed data from your region or other geography.

**Comment by stevenhz** [comment]
Dear joecastiglione, 

Thanks for your answer for Q1.  For Q2, I would elaborate it a bit more:
1. 10% of the total HH is used for simulation, shadow pricing is disabled. As far as I understand, shadow pricing is recommended for full samples.
2. The ratio between the number of work tours and school tours from the simulation is 2.2
3.  The ratio from the survey data is about 1.29. However, the survey reports that the work/school ratio is normally 1.6~1.8. So the ratio in the survey data which I use is a bit low.
4.  In the land use data, the number of employments is about 2x of the number of students.

I don't have a parameter estimation for destination choice yet. So in this case, I am wondering which direction I should go:
- leave as it is, so trusts the land use data
- adjust the model parameters to fit closer to survey data. I fully agree this is not a good option.  However, so far, adjusting the mandatory tour frequency ASC parameter seems not to have any effect. The ratio in the simulation results does not change. Do you have any advice?
- do estimation for the destination choice, so trusts the survey data.

Thank you and looking forward to your reply.

**Comment by jfdman** [comment]
Hi, thought I'd chime in here. The number of work and school tours is directly related to the attributes of the synthetic population, not the input land-use data. If you are getting too many or too few work or school tours, a good starting point is to look at how work status and school status are coded in the synthetic population, and the number of workers/students in the synthetic population compared to the actual population of the region you are modeling. 

The location choice of workers and students is affected by the spatial distribution of jobs and enrollment, rather than the absolute value.  And the generation of actual work and school tours comes AFTER usual work and school location choice.

**Comment by stevenhz** [comment]
Hi Joel,  thanks for your explanation.
