### ISSUE TITLE
np.MachAr Deprecated: Tests Failing

### ISSUE THREAD

**Issue by danielsclint** [ActivitySim/activitysim#533]
The latest release of Numpy (v1.22) deprecated [np.MachAr](https://github.com/numpy/numpy/pull/20201). This cause the Numba decorators in ActivitySim's [initialize_los](https://github.com/ActivitySim/activitysim/blob/master/activitysim/abm/models/initialize_los.py) module to fail.

**Comment by jpn--** [comment]
This is a known issue in numba when running with numpy 1.22. https://github.com/numba/numba/issues/7758

Going to constrain us to numpy 1.21 until numba is fixed.
