### ISSUE TITLE
Document skim definitions for MTC Example

### ISSUE THREAD

**Issue by stefancoe** [ActivitySim/activitysim#541]
A detailed list of skims, including a description of each skim measure and units, would really help implementation. We have been relying on these:

https://activitysim.github.io/activitysim/examples.html#trip-modes
https://github.com/BayAreaMetro/modeling-website/wiki/TravelModes

I vaguely remember another link so perhaps it already exists.

**Comment by stefancoe** [comment]
For example, we are trying to figure out what the skims on line this [line](https://github.com/ActivitySim/activitysim/blob/master/activitysim/examples/example_mtc/configs/accessibility.csv#L23) are representing. For one, how are the 'TRN' skims different from the transit sub mode specific skims such as 'LOC'? Do they represent the best (least) transit impedance for each OD? Secondly, if 'WACC' and 'WEGR' are the walk access and egress components, what is 'WAUX'? The walk component when transferring?

skim_od[('WLK_TRN_WLK_IWAIT', 'AM')] + skim_od[('WLK_TRN_WLK_XWAIT', 'AM')] + skim_od[('WLK_TRN_WLK_WACC', 'AM')] + skim_od[('WLK_TRN_WLK_WAUX', 'AM')] + skim_od[('WLK_TRN_WLK_WEGR', 'AM')]

**Comment by mnbina** [comment]
MTC to update this page: https://github.com/BayAreaMetro/modeling-website/wiki/SimpleSkims
The activitysim documentation (https://activitysim.github.io/activitysim/examples.html#trip-modes) can link to the updated MTC Simple Skims page .

**Comment by FlaviaTsang** [comment]
Hi @stefancoe, thanks for letting us know about these gaps in our documentation. To address your questions, I added a TransitSkims page to our wiki: https://github.com/BayAreaMetro/modeling-website/wiki/TransitSkims. 

About the generic TRN skims, they represent paths found in which all line-haul modes are treated equally. They are created for accessibility calculations. Please see a more detailed explanation under the bullet “What is the generic transit path?” in the TransitSkims documentation.

To the question about “WAUX”, they represent the transfer between walk auxiliary node and station platform node - this is now documented in a table in the TransitSkims documentation. 

I hope the updated documentation is helpful. Please feel free to let us know if you have any further questions.

**Comment by stefancoe** [comment]
Hi @FlaviaTsang, thanks for adding the documentation- it's super helpful!

**Comment by stefancoe** [comment]
Hi @FlaviaTsang - sorry to revisit this issue. In the [documentation](https://github.com/BayAreaMetro/modeling-website/wiki/TransitSkims) you posted it says:

'In comparison, the non-generic line-haul mode skims have mode-specific perceived time factors that are set to be lower for the given line-haul mode than other line-haul modes.'

Just to clarify, do the skims themselves represent the perceived time or do they represent actual time and perceived time is only used for path building? 

Thanks!

**Comment by FlaviaTsang** [comment]
Hi @stefancoe, the skims themselves represent actual time and perceived time is only used for path building. I'll update the documentation to make sure that this is clear. Thank you for pointing this out!

**Comment by stefancoe** [comment]
Thank you @FlaviaTsang !
