### ISSUE TITLE
Need OP_SKIMS in trip destination model / error in ARC example model

### ISSUE THREAD

**Issue by jpn--** [ActivitySim/activitysim#545]
There is a line in the spec for the example ARC model marked with the comment:

> THIS IS WRONG ***** RIGHT HERE **** I CHANGED THE BELOW TO MAKE WORK MECHANICALLY

https://github.com/ActivitySim/activitysim/blob/master/activitysim/examples/example_arc/configs/trip_destination.csv#L16

It appears that whomever was building this file wanted to access three kinds of skim references:
1. od_skims = fixed-origin to stop-location
2. dp_skims = stop-location to fixed-primary-destination
3. op_skims = fixed-origin to fixed-primary-destination (as if there was no stop)

The third type is not used in the canonical MTC model for trip destination, and it seems it was never coded into the trip destination component for ActivitySim.  The current ARC example is just using the od_skims again as a placeholder for the missing op_skims to make it work "mechanically" (i.e. not crash) but it sure looks to me like the model spec file is wrong.  The fix requires:

- [x] Make op_skims available in the trip destination component (and by extension, opt_skims; we can probably skip po_ and pot_)
- [ ] Correct the trip destination spec file in prototype_arc 
- [ ] Verify outputs from prototype_arc model
- [ ] Update tests

Note to developers: Do not close this issue until @guyrousseau (or his designee) can confirm that ARC gets the fix in their agency-maintained model as well, and not just in the consortium's example model.  cc: @i-am-sijia

**Comment by guyrousseau** [comment]
Thanks Jeff for bringing this up to our attention. Indeed the ARC ActivitySim example is merely a prototype model application at this point in time. That said, we at ARC will confer with @i-am-sijia at WSP to get this taken care of, in accordance with your aforementioned observations and suggestions. Hence for now, this issue shall remain open until properly addressed and resolved.

**Comment by jfdman** [comment]
@dhensle please see this issue - I believe this is being addressed by the SANDAG "trip" (really stop) destination choice model - please advise.

**Comment by jpn--** [comment]
At this time, the infrastructure to allow for op_skims has been merged into ActivitySim, but as yet there is no example model or test that implements the change.

**Comment by i-am-sijia** [comment]
I updated and tested the ARC example model with the change, will create a PR to reflect that.

**Comment by jfdman** [comment]
I see the updated ARC stop model is in the latest release, closing issue.
