### ISSUE TITLE
larch conflicts with skims.omx

### ISSUE THREAD

**Issue by XumingGao** [ActivitySim/activitysim#573]
We have packaged some python files for convenience. And when packaging estimation codes together, there are conflicts if we import larch. The '_read_skims_from_omx' part fails. The 'skims.omx' contains 116 skim matrices but 0 read.
We downloaded larch with 5.6.1 and asim 1.0.4.
Is that a general issue?

**Comment by jpn--** [comment]
I’m not clear on what you mean by “ packaged some python files for convenience”. Can you elaborate?

If you are moving files around, it is possible your skim reading is not finding the files to read at all.  Is it raising an error with a trace back you can share?

**Comment by XumingGao** [comment]
Well, the estimation work needs to run Activitysim Estimation Mode first and then Larch Jupyter Notebooks, separately. We wrote a PY file to gather both parts' codes and try to run it automatically. And we failed at the omx read part. The log file named 'failed with larch imported.log' is shared below. Even if we removed the second part codes(codes in the Notebooks), the error log remains the same as well as we still import larch. The py file with second part codes removed and import code left is also shared, named 'run_est_importlarch.txt'.
However, if the import code is removed, the reading skim omx part will succeed. The 'run_est_succeed.txt' and 'succeed log.log' are shared as well.
All the tests are using the same data files and path configs.
[failed with larch imported.log](https://github.com/ActivitySim/activitysim/files/8949925/failed.with.larch.imported.log)
[succeed log.log](https://github.com/ActivitySim/activitysim/files/8949979/succeed.log.log)
[run_est_importlarch.txt](https://github.com/ActivitySim/activitysim/files/8949985/run_est_importlarch.txt)
[run_est_succeed.txt](https://github.com/ActivitySim/activitysim/files/8950018/run_est_succeed.txt)

**Comment by jfdman** [comment]
@XumingGao  - has this issue been resolved? if so please close the issue.
