### ISSUE TITLE
[Bug] Parking location choice not using landuse attributes from alternative parking zones

### ISSUE THREAD

**Issue by i-am-sijia** [ActivitySim/activitysim#620]
## Describe the bug
The current parking location choice model uses landuse attributes (such as parking cost, parking capacity) from trip destination zones instead of from alternative parking zones. This is problematic as it results in the same parking cost for all alternatives. Code changes are required to bring in attributes from alternative parking zones for the model.

For example, the table below shows a snapshot of the parking location choosers dataframe from the MTC TM2 implementation using the ActivitySim/develop codes. You can see the values of parking attributes (column CJ-CS) are not changing by alternative parking zones (column B). In the correct implementation, the values of parking attributes should vary based on the alternative parking zones.

![image](https://user-images.githubusercontent.com/28812722/197870848-7cccb0db-d560-41e2-ae30-e999eb81a531.png)

### Triggering line of code
This is the line that's dropping columns from alternative zones (the comment is incorrect, we do need size terms in alternatives):

https://github.com/ActivitySim/activitysim/blob/7ead422df617384ea9cd113b6ff84a2297632053/activitysim/abm/models/parking_location_choice.py#L231-L233

This is the line that's dropping columns from destination sample zones:
https://github.com/ActivitySim/activitysim/blob/7ead422df617384ea9cd113b6ff84a2297632053/activitysim/abm/models/parking_location_choice.py#L174

Size terms are obtained from destination zones in the [example implementation](https://github.com/ActivitySim/activitysim/blob/develop/activitysim/examples/prototype_arc/configs/parking_location_choice_annotate_trips_preprocessor.csv#L5-L8).

### Thoughts on resolution
WSP has implemented the code changes to bring in attributes from alternative parking zones as part of the MTC ActivitySim implementation. Code changes are currently under review, and will be brought into SANDAG's ActivitySim implementation. WSP will create a pull request to the consortium repo once the review is done.

After this fix, the choosers dataframe looks like the screenshot below, the values of parking attributes vary based on the alternative parking zones.

![image](https://user-images.githubusercontent.com/28812722/197871014-89ffc849-3260-4eb4-abce-a956eaa15372.png)

@guyrousseau - @sidharthanr will update the ARC implementation to incorporate this fix.

**Comment by guyrousseau** [comment]
Thanks @i-am-sijia for uncovering this, does it trace all the way back to our CT-RAMP https://atlregional.github.io/ARC_Model/TripLevelModels.html#section_55_parking_location_choice or is it something specific and unique to ActivitySim?

**Comment by sidharthanr** [comment]
@guyrousseau . ARC CT-RAMP does not have this issue. In fact after the ASIM bug fix, the results from ARC CT-RAMP and ARC ASIM matches really well now. Please see the before vs. after comparisons below.

![image](https://user-images.githubusercontent.com/11063779/198062991-24ce662b-a474-4fb5-bd30-fb33e767d152.png)

![image](https://user-images.githubusercontent.com/11063779/198063038-9a03573d-5e7e-4f2c-a615-a02b457d01d1.png)

**Comment by guyrousseau** [comment]
Thanks @sidharthanr, this is very re-assuring, featuring a pretty high R-Squared value / coefficient of determination, so all is well between our ARC ActivitySim implementation and our ARC CT-RAMP "production" model ABM from a comparative perspective, regarding the formulation of the parking location choice model.

**Comment by i-am-sijia** [comment]
> Thanks @i-am-sijia for uncovering this, does it trace all the way back to our CT-RAMP https://atlregional.github.io/ARC_Model/TripLevelModels.html#section_55_parking_location_choice or is it something specific and unique to ActivitySim?

It is a bug just in ActivitySim, not CTRAMP. @sidharthanr has adopted and confirmed the fix for ARC ActivitySim.
