### ISSUE TITLE
SEMCOG ActivitySim Runtime Performance Issues with various Chuck settings 

### ISSUE THREAD

**Issue by JilanChen** [ActivitySim/activitysim#628]
Machine Specs: AMD® Ryzen™ Threadripper™ Pro 5995WX Processor, 64-core / 128-thread @ 2.7GHz, 512 GB RAM
Total ActivitySim Run Time (summary of timing_log) with 100% samples (1.9 million households), two-zone system (3k zones & 28k micro-zones): 
20 processors and 200 GB RAM: 557 minutes 
40 processors and 400 GB RAM: 850 minutes
60 processors and 450 GB RAM: 1080 minutes

Using new training from this machine doesn't help either. 20 processors and 200 GB RAM runtime seems consistent with the runtime in another intel machine. Any tips on anything wrong with my settings or AMD processors?

**Comment by bettinardi** [comment]
A quick note that we found something similar several years ago with our statewide model - more processors actually slowed down our overall run time significantly.  What we found was that we were not optimatized to take advantage of that many processors, so the issue was two fold; on one side we were losing speed because as you add processors you usually lose speed (GHZ) for each individual processor; 2) we were losing time in overhead to distribute inefficiently across more processors than we were setup to use.  We tested many configurations and found that the sweet spot for us was between 8 and 16 processors.  We turned around and bought the best (highest speed) processors we could with 8 processors (16 threads).  This also saved us significant dollars.  The fast 8 processors were about $3500 (4-5 years ago).  This is in comparison to the 20 processor machines we had to return (because of how slow they were for our work) at $7500

**Comment by guyrousseau** [comment]
At ARC for ABM modeling, one of our server's systems contains 64 cores of processor (so 128 threads), 512 GB of RAM, a mix of SSD and Serial-Attached SCSI solid-state drives, and plenty of room to grow as needed.  That one is a Dell PowerEdge R840 Server with Intel Xeon Gold 6130 processors (no AMDs at ARC). Overnight ABM run-times have been manageable and somewhat satisfactory thus far, though we're no longer investing in servers anymore, all cloud-based computing solutions (mostly AWS) from this point forward, with a greater emphasis on that trajectory in 2023 and beyond.

**Comment by JilanChen** [comment]
> 

Thanks for the tips! I'll test 20 processors and 400 GB RAM next for the purpose of comparison.

**Comment by JilanChen** [comment]
> 

That's our first time to try out AMD since it's much cheaper comparing to the same specs of Intel.

**Comment by jpn--** [comment]
Counterintuitively (although based on the evidence above, not actually...) I would suggest also testing with even fewer processors.  I suspect you are seeing the results you are because you are flooding the CPU cache, as ActivitySim is very memory-intensive.

**Comment by JilanChen** [comment]
> Counterintuitively (although based on the evidence above, not actually...) I would suggest also testing with even fewer processors. I suspect you are seeing the results you are because you are flooding the CPU cache, as ActivitySim is very memory-intensive.

Yes, it's in my plan too.

**Comment by stefancoe** [comment]
@JilanChen Can you share the timing_log.csv for a couple of these runs? It would be interesting to see the run times broken down by model step.

**Comment by JilanChen** [comment]
> 

Another AMD machine in SEMCOG (with similar specs) seems running much faster than the one I reported. RSG is going to look into that machine to see if there are any problems with settings. Once that is done, I will put the run times together in these machines and share with the group.

**Comment by guyrousseau** [comment]
As an additional point of comparison, below is the ARC timing_log.csv output file from a 1.0.4 version ActivitySim baseline / base-year model run. Destination choice and scheduling models are the ones taking the most time, relatively speaking.

process_name | model_name | seconds | minutes
-- | -- | -- | --
mp_initialize_landuse | initialize_landuse | 0.9 | 0
mp_accessibility_0 | compute_accessibility | 8 | 0.1
mp_initialize_households | initialize_households | 148.1 | 2.5
mp_households_0 | school_location | 506.5 | 8.4
mp_households_0 | workplace_location | 2043 | 34
mp_households_0 | auto_ownership_simulate | 14.4 | 0.2
mp_households_0 | free_parking | 12.5 | 0.2
mp_households_0 | cdap_simulate | 69.4 | 1.2
mp_households_0 | mandatory_tour_frequency | 21.6 | 0.4
mp_households_0 | mandatory_tour_scheduling | 6832.4 | 113.9
mp_households_0 | joint_tour_frequency | 28.8 | 0.5
mp_households_0 | joint_tour_composition | 22 | 0.4
mp_households_0 | joint_tour_participation | 38.8 | 0.6
mp_households_0 | joint_tour_destination | 355.4 | 5.9
mp_households_0 | joint_tour_scheduling | 926.6 | 15.4
mp_households_0 | non_mandatory_tour_frequency | 829 | 13.8
mp_households_0 | non_mandatory_tour_destination | 1341 | 22.3
mp_households_0 | non_mandatory_tour_scheduling | 7769 | 129.5
mp_households_0 | tour_mode_choice_simulate | 201.7 | 3.4
mp_households_0 | atwork_subtour_frequency | 39.6 | 0.7
mp_households_0 | atwork_subtour_destination | 474.9 | 7.9
mp_households_0 | atwork_subtour_scheduling | 465.2 | 7.8
mp_households_0 | atwork_subtour_mode_choice | 49.6 | 0.8
mp_households_0 | stop_frequency | 176.1 | 2.9
mp_households_0 | trip_purpose | 37.5 | 0.6
mp_households_0 | trip_destination | 13762.6 | 229.4
mp_households_0 | trip_purpose_and_destination | 107.9 | 1.8
mp_households_0 | trip_scheduling_choice | 343.5 | 5.7
mp_households_0 | trip_departure_choice | 146 | 2.4
mp_households_0 | trip_mode_choice | 315.1 | 5.3
mp_households_0 | parking_location | 71.9 | 1.2
mp_households_0 | write_data_dictionary | 76.1 | 1.3
mp_households_0 | track_skim_usage | 9.1 | 0.2
mp_summarize | write_trip_matrices | 521.8 | 8.7
mp_summarize | write_tables | 749.9 | 12.5

**Comment by JilanChen** [comment]
> Destination

Guy, is your 

> As an additional point of comparison, below is the ARC timing_log.csv output file from a 1.0.4 version ActivitySim baseline / base-year model run. Destination choice and scheduling models are the ones taking the most time, relatively speaking.
> 
> process_name	model_name	seconds	minutes
> mp_initialize_landuse	initialize_landuse	0.9	0
> mp_accessibility_0	compute_accessibility	8	0.1
> mp_initialize_households	initialize_households	148.1	2.5
> mp_households_0	school_location	506.5	8.4
> mp_households_0	workplace_location	2043	34
> mp_households_0	auto_ownership_simulate	14.4	0.2
> mp_households_0	free_parking	12.5	0.2
> mp_households_0	cdap_simulate	69.4	1.2
> mp_households_0	mandatory_tour_frequency	21.6	0.4
> mp_households_0	mandatory_tour_scheduling	6832.4	113.9
> mp_households_0	joint_tour_frequency	28.8	0.5
> mp_households_0	joint_tour_composition	22	0.4
> mp_households_0	joint_tour_participation	38.8	0.6
> mp_households_0	joint_tour_destination	355.4	5.9
> mp_households_0	joint_tour_scheduling	926.6	15.4
> mp_households_0	non_mandatory_tour_frequency	829	13.8
> mp_households_0	non_mandatory_tour_destination	1341	22.3
> mp_households_0	non_mandatory_tour_scheduling	7769	129.5
> mp_households_0	tour_mode_choice_simulate	201.7	3.4
> mp_households_0	atwork_subtour_frequency	39.6	0.7
> mp_households_0	atwork_subtour_destination	474.9	7.9
> mp_households_0	atwork_subtour_scheduling	465.2	7.8
> mp_households_0	atwork_subtour_mode_choice	49.6	0.8
> mp_households_0	stop_frequency	176.1	2.9
> mp_households_0	trip_purpose	37.5	0.6
> mp_households_0	trip_destination	13762.6	229.4
> mp_households_0	trip_purpose_and_destination	107.9	1.8
> mp_households_0	trip_scheduling_choice	343.5	5.7
> mp_households_0	trip_departure_choice	146	2.4
> mp_households_0	trip_mode_choice	315.1	5.3
> mp_households_0	parking_location	71.9	1.2
> mp_households_0	write_data_dictionary	76.1	1.3
> mp_households_0	track_skim_usage	9.1	0.2
> mp_summarize	write_trip_matrices	521.8	8.7
> mp_summarize	write_tables	749.9	12.5

Thanks, Guy. Your total ActivitySim run time seems over 10 hours also. SEMCOG needs 4 iterations to get the traffic flow to converge.  SEMCOGS's work_location model takes the longest time (2-zone with Shadow prince on).

**Comment by JilanChen** [comment]
Below is the SEMCOG timing_log.csv file from three machines. 
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/chen/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/chen/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



Computer   Specs | Computer One -   Intel(R) Xeon(R) Gold 6146 CPU @ 3.20GHz, 24 Cores, 256 GB RAM | Computer Two - AMD®   Ryzen™ Threadripper™ Pro 3995WX, 64-core @ 2.7GHz, 512GB RAM | Computer Three - AMD®   Ryzen™ Threadripper™ Pro 5995WX, 64-core    @ 2.7GHz, 512 GB RAM
-- | -- | -- | --
num_processes | 10 | 20 | 10 | 40 | 10 | 40 | 40 | 40
chunk_size (GB) | 200 | 200 | 450 | 450 | 400 | 400 | 400 | 400
process_name | model_name (100% Samples) | Feedback | Feedback | Feedback | Feedback | Feedback | Feedback | Training | Prodcution
mp_initialize | initialize_landuse | 0.5 | 0.5 | 0.4 | 0.4 | 0.4 | 0.4 | 0.4 | 0.4
mp_initialize | initialize_households | 1.9 | 1.6 | 1.2 | 1.2 | 1.3 | 1 | 1.1 | 1
mp_accessibility_0 | compute_accessibility | 7.8 | 4.7 | 3.6 | 4 | 3.3 | 3.4 | 4 | 3.4
mp_households_0 | school_location | 16.5 | 16.6 | 13 | 7.7 | 11.3 | 10.6 | 32.1 | 10.7
mp_households_0 | university_location_zone_override | 0.1 | 0.1 | 0.1 | 0 | 0.1 | 1.1 | 0 | 0
mp_households_0 | workplace_location | 275.8 | 285.8 | 184.7 | 91.4 | 241.6 | 456.4 | 657.4 | 350.3
mp_households_0 | work_from_home | 0.2 | 0.2 | 0.1 | 0.1 | 0.1 | 0.1 | 0.1 | 1.5
mp_households_0 | transit_pass_subsidy | 0.2 | 0.2 | 0.1 | 0.1 | 0.1 | 0.1 | 0.1 | 0.4
mp_households_0 | transit_pass_ownership | 0.2 | 0.1 | 0.1 | 0.1 | 0.1 | 0 | 0.1 | 0
mp_households_0 | auto_ownership_simulate | 0.1 | 0.1 | 0 | 0 | 0 | 0 | 0.1 | 0
mp_households_0 | free_parking | 0.2 | 0.1 | 0.1 | 0.1 | 0.1 | 2 | 0.1 | 0.1
mp_households_0 | telecommute_frequency | 0.2 | 0.1 | 0.1 | 0.1 | 0.1 | 0.1 | 1.9 | 0
mp_households_0 | cdap_simulate | 0.4 | 0.3 | 0.3 | 0.2 | 0.3 | 0.2 | 1.3 | 0.2
mp_households_0 | mandatory_tour_frequency | 0.2 | 0.1 | 0.2 | 0.1 | 0.2 | 0.1 | 0.1 | 0.1
mp_households_0 | mandatory_tour_scheduling | 40.8 | 27.3 | 27 | 14.9 | 37.6 | 50.2 | 105.7 | 50.9
mp_households_0 | joint_tour_frequency | 0.2 | 0.4 | 0.1 | 0.1 | 0.1 | 0.1 | 0.3 | 1.1
mp_households_0 | joint_tour_composition | 0.1 | 0.3 | 0.1 | 0.1 | 0.1 | 0.1 | 3.4 | 0.6
mp_households_0 | joint_tour_participation | 0.4 | 0.5 | 0.3 | 0.2 | 0.3 | 0.1 | 0.3 | 0.1
mp_households_0 | joint_tour_destination | 3.7 | 3.7 | 2.7 | 1.4 | 2.4 | 5.4 | 31.3 | 3.3
mp_households_0 | joint_tour_scheduling | 6.4 | 3.6 | 4.3 | 1.6 | 4 | 4 | 10.7 | 4.6
mp_households_0 | non_mandatory_tour_frequency | 5.2 | 4.3 | 3.9 | 2.1 | 5.4 | 8.3 | 20.4 | 8.9
mp_households_0 | non_mandatory_tour_destination | 27.6 | 15.9 | 20.7 | 9.6 | 21.8 | 33.3 | 75.9 | 34.7
mp_households_0 | non_mandatory_tour_scheduling | 46.4 | 55.1 | 31.7 | 18 | 36 | 49.6 | 213.7 | 49.6
mp_households_0 | tour_mode_choice_simulate | 2.6 | 2.2 | 1.9 | 1 | 1.7 | 2.9 | 17.7 | 2.8
mp_households_0 | atwork_subtour_frequency | 0.2 | 0.2 | 0.2 | 0.1 | 0.2 | 0.1 | 0.3 | 0.1
mp_households_0 | atwork_subtour_destination | 5.2 | 4.3 | 3.8 | 3 | 3.7 | 8.7 | 125.1 | 10.1
mp_households_0 | atwork_subtour_scheduling | 2.2 | 2.4 | 1.5 | 0.7 | 1.4 | 2.6 | 8.5 | 0.6
mp_households_0 | atwork_subtour_mode_choice | 0.4 | 0.4 | 0.3 | 0.2 | 0.2 | 0.1 | 1.1 | 1.5
mp_households_0 | stop_frequency | 1 | 1.4 | 0.7 | 0.5 | 0.7 | 1.1 | 11.1 | 0.7
mp_households_0 | trip_purpose | 0.2 | 0.3 | 0.1 | 0.1 | 0.1 | 1 | 0.2 | 0
mp_households_0 | trip_destination | 125.2 | 102.9 | 84.2 | 57.2 | 78.2 | 167.7 | 1476.1 | 237.3
mp_households_0 | trip_purpose_and_destination | 3 | 0.3 | 1.2 | 0.1 | 2.2 | 0.1 | 0.9 | 0.1
mp_households_0 | trip_destination_univ_zone_override | 0.1 | 0.2 | 0.1 | 0.1 | 0.1 | 0.1 | 1 | 0
mp_households_0 | parking_location_choice_at_university | 0.1 | 0.2 | 0.1 | 0.1 | 0.1 | 0.1 | 0.2 | 0
mp_households_0 | trip_scheduling | 2.9 | 2 | 2.3 | 0.8 | 2 | 1.7 | 164.2 | 2.6
mp_households_0 | stop_frequency_university_parking | 0.1 | 0.2 | 0.1 | 0.1 | 0.1 | 1 | 0 | 0
mp_households_0 | trip_mode_choice | 15.7 | 21 | 11.3 | 11.4 | 10.9 | 27.1 | 221.4 | 72.9
mp_summarize | write_data_dictionary | 1.1 | 1.1 | 0.9 | 0.9 | 0.8 | 0.7 | 0.8 | 0.7
mp_summarize | write_tables | 6.1 | 6 | 5.5 | 5.5 | 4.5 | 4.4 | 4.4 | 4.4
mp_summarize | write_trip_matrices | 7.5 | 13.2 | 4.8 | 4.4 | 4.5 | 3.7 | 4.5 | 3.7
  |   | 608.7 | 579.9 | 413.8 | 239.7 | 478.1 | 849.7 | 3198 | 859.4
Reference   Runtime of TransCAD procedures |   |   |   |   |   |   |   |  
TransCAD | Transit Skims | 03:31:34 | 1:48:43 | 12:12 | 12:45 | 09:52 | 09:33 |   |  
TransCAD | Process Transit Skim | 38:54 | 40:21 | 9:22 | 9:42 | 09:02 | 08:53 |   |  
ActivitySim | Pre-processing | 18:34 |   | 15:08 | 16:05 | 14:08 | 12:59 |   |  
ActivitySim | ActivitySim | 10:30:51 | 13:22:28 | 7:15:57 | 4:18:22 | 8:11:22 | 14:27:38 |   |  
ActivitySim | Post-processing | 11:37 |   | 7:52 | 7:56 | 06:45 | 7:39 |   |  
TransCAD | Assignment | 56:31 | 55:30 | 45:35 | 47:29 | 33:32 | 32:45 |   |  
  |   |   |   |   |   |   |   |   |  
Total Run   Time of 4 Feedbacks (50%, 75%, 100%, 100%) | 58 hours | 57 hours | 30 hours | 19 hours | 32 hours | 54 hours |   |  
  |   |   |   |   |   |   |   |   |  



</body>

</html>

**Comment by JilanChen** [comment]
Below is the SEMCOG timing_log.csv from three computers.
![image](https://user-images.githubusercontent.com/16387511/208707893-76557b43-bd5e-4224-a72d-87e06490451b.png)
