### ISSUE TITLE
User’s Guide Phase I

### ISSUE THREAD

**Issue by jpn--** [ActivitySim/activitysim#648]
CS will develop a draft ActivitySim user guide, targeting model users and analysts, rather than model developers.    This document will provide guidance on topics such as installing ActivitySim, manipulating model input data, configuring and running ActivitySim models, and comparing and visualizing outputs.  CS will work with consortium partners to identify the specific content to be included in the user guide.  CS will identify, edit and consolidate existing ActivitySim documentation content for the user’s guide, but generation of brand new documentation content sections is not included in this task.

**Comment by stefancoe** [comment]
@jpn-- I am hoping this will include better documentation of maz_to_maz bike and walk impedances with some more detail about the blending parameters (e.g. max_blend_distance) and exactly how they work. Also, the existing documentation says:

"Users can also override transit walk access and egress times with times specified in the MAZ file by transit mode. Careful pre-calculation of the assumed transit walk access and egress time by MAZ and transit mode is required depending on the network scenario."

I imagine this is just referring to the fact that you can specify a land use column [like so](https://github.com/ActivitySim/activitysim/blob/main/activitysim/examples/prototype_mtc/configs/tour_mode_choice_annotate_choosers_preprocessor.csv#L27), but it is not obvious how to do it from the limited description. So if that part is kept, perhaps show/describe an example. 
 
https://activitysim.github.io/activitysim/v1.2.0/examples.html?highlight=maz_to_maz#placeholder-multiple-zone

Thanks!
