### ISSUE TITLE
tot_tours Hidden in Non-Mandatory Tour Frequency Code

### ISSUE THREAD

**Issue by dhensle** [ActivitySim/activitysim#656]
A variable named `tot_tours` is hard-coded in the non-mandatory tour frequency model: https://github.com/ActivitySim/activitysim/blob/main/activitysim/abm/models/non_mandatory_tour_frequency.py#L159.  
This should really be exposed to the user and listed in the alternatives file instead.

**Comment by JoeJimFlood** [comment]
@dhensle Is what I did in #661 along the lines with what you were thinking? I am wondering if we should add a check that the total tours is actually the total number of nonmandatory tours for each alternative and raise an AssertionError if that's the case.
