### ISSUE TITLE
Pandas 2.0

### ISSUE THREAD

**Issue by jpn--** [ActivitySim/activitysim#663]
[Pandas 2.0](https://pandas.pydata.org/docs/dev/whatsnew/v2.0.0.html) was released on April 3.  It has some exciting new features.  Also it will break ActivitySim v1.2.0, so don't use it yet.

Fixes are in progress, this issue will be updated with the status of fixes when they are complete.

**Comment by dhensle** [comment]
Closing in favor of #794.
