### ISSUE TITLE
skip_sharrow setting doesn't work for some model steps

### ISSUE THREAD

**Issue by JoeJimFlood** [ActivitySim/activitysim#674]
In order to get the latest ABM3 setup to run through while compiling Sharrow, I needed to skip it in a few steps. However, there are at least a couple of steps where the option doesn't work. @dhensle showed me how to edit the CDAP code to just not run Sharrow, and then I did something similar in joint tour frequency and composition.

**Comment by jpn--** [comment]
Yeah, unfortunately ActivitySim has a lot of unique components, many of which use inconsistent settings or step through their computational processes in different ways.  It makes it hard to take a "skip" message from a component config file and deliver it to the sharrow `apply_flow` through the mess of intermediate function calls.  We can work on this as part of the general refactoring of component configs.

**Comment by jpn--** [comment]
This is now addressed in #842, which provides a common interface pathway for sharrow control (skip, fastmath, and others potentially in the future)
