### ISSUE TITLE
Feature: Parking capacity (supply) modeling

### ISSUE THREAD

**Issue by lmz** [ActivitySim/activitysim#701]
Historically, parking capacity constraint has either been entirely absent from modeling systems, been used to constrain drive choices to PNR lots, or been used to constrain or redirect parking in dense urban cores.  Depending on the level of policy sensitivity desires, and criticially constrained by the amount and detail of available parking data, parking capacity constrain could be extended to be explicitly considered when making drive choices.  In an unreleased enhancement to the San Francisco Daysim model, parking capacity constraint was extended to explicitly account for onstreet parking supply (free, free permit required, paid meter) as well as off-street parking supply.

Added from `ActivitySim Budget Phase 9.xslx`

**Comment by lmz** [comment]
Comments from prior discussion:

- ODOT: If we were to move foward with this, we might want to consider some type of curbside drop-off capacity feedback as well...  seems like if we were going to go to this level of inventory detail and modeling complexity we wouldn't want to mis curbside concepts.

- SFCTA: We need to be cautious about what data is required to drive any of the proposed model enhancements.  Data on PNR lot capacities is tractable for all regions.  Data on parking lots may be available in some regions but not all.  Data on all curb parking capacity is highly unlikely to exist in most regions.  We also need to be cognizant of the geographic resolution / granularity of the model.  Most models are still operating at relatively aggregate zones and networks, although there is increased movement towards ""all streets"" networks with the advent of OSM and commercial network data products.  I think it might be worth holding off on this until there a clearer need driving it, and more of our modeling systems incorporate an appropriate level of geographic detail.

- SEMCOG: I like the idea to put all parking related models next to each other to have a full picture of what current ActivitySim can handle and what else should be enhanced or added.

- PSRC- Perhaps implement the Daysim approach- account for the number of external workers coming to a TAZ, then make that number of jobs unavailable for work location model. In the other direction, reduce the number of workers able to make work tours for each TAZ by the number of workers that work externally. This does require that ixxi trips are handled in a separate step and it would be nice if this could be automated using LEHD, but not sure if that is within AcitivtySim's domain.

- MTC: Transit station parking capacity seems both more useful (because it affects transit ridership) and tractable (PNR supply vs all parking).  Would prioritize that and not the generic version; rank transit PNR as high, general version low.

- OR-DOT - we (Oregon) are hoping to be able to code car-free districts - no cars allowed - no vehicle travel time options... Similar to not having the ability to access a given zone by transit...

**Comment by joecastiglione** [comment]
Closed issue, consolidated with https://github.com/ActivitySim/activitysim/issues/712
