### ISSUE TITLE
generic zone labels other than 'TAZ'

### ISSUE THREAD

**Issue by bstabler** [ActivitySim/activitysim#75]
@wusun2 - would like support for generic zone labels other than 'TAZ'.  This raises a question about the boundary between what the developer is responsible for and what the modeler is responsible for.  TAZ is currently hard wired into many of the activitysim/defaults/tables and activitysim/defaults/models classes, probably because it is in the initial input HDF5 data.  Is the goal for the modeler setting up a new model to not need to revise these classes?  We'll come back to this issue later in the project.

**Comment by e-lo** [comment]
Can this just resolved by renaming it "zone" find/replace?

**Comment by bstabler** [comment]
Partially.  We also need to revise the example data, the scripts that prepare the example data, and the documentation.  I suggest we deal with this when we start to tackle multiple zone systems.

**Comment by bstabler** [comment]
This is related to the work going on [here](https://github.com/UDST/activitysim/wiki/Multiple-Zone-Systems-Design)

**Comment by bstabler** [comment]
As explained in the [latest example settings file](https://github.com/ActivitySim/activitysim/blob/master/activitysim/examples/example_mtc/configs/settings.yaml), with the release of support for multiple zone systems, we standardized on activitysim using "well-known" index and foreign key names for imported tables as well as for created tables.  As a result, the zone label is now "zone_id" and if your input file has a different field (such as "TAZ") then you can rename it on import from "TAZ" to "zone_id".
