### ISSUE TITLE
Outbound & Inbound definition in the trip data

### ISSUE THREAD

**Issue by egemenokten** [ActivitySim/activitysim#750]
Hello,

I'm trying to implement ActivitySim with my survey data. Right now i'm working on estimation module and trying to convert my trip data into ActivitySim format. But i didn't understand ``outbound`` parameter in ``survey_trips.csv``. 

In the example data in ActivitySim repo;

**Example 1**
```
trip_id,person_id,household_id,tour_id,outbound,purpose,destination,origin,depart,trip_mode
3977921,12127,12127,497240,True,othmaint,742,725,14.0,DRIVEALONEFREE
3977922,12127,12127,497240,True,shopping,733,742,16.0,TNC_SINGLE
3977925,12127,12127,497240,False,Home,725,733,17.0,TNC_SINGLE
```
**Example 2**
```
trip_id,person_id,household_id,tour_id,outbound,purpose,destination,origin,depart,trip_mode
15469337,47162,47162,1933667,True,othdiscr,494,520,15.0,DRIVEALONEFREE
15469341,47162,47162,1933667,False,othmaint,466,494,16.0,TNC_SHARED
15469342,47162,47162,1933667,False,Home,520,466,16.0,DRIVEALONEFREE
```

Second trip labeled as outbound in the first example, but labeled as inbound in the second example. What is the difference these two ? Can someone please explain the definition of outbound and inbound? Is this related with trips to the city center and outside the city center?

**Comment by jfdman** [comment]
Outbound refers to trips between the tour origin and the tour primary destination, and inbound refers to trips between the tour primary destination back to the tour origin. So for a work tour, outbound trips are between home and work and inbound trips are between work and home.

**Comment by egemenokten** [comment]
Thanks Joel !
