### ISSUE TITLE
School Escort uses too much memory

### ISSUE THREAD

**Issue by jpn--** [ActivitySim/activitysim#786]
...

**Comment by dhensle** [comment]
Some low-hanging fruit to be addressed first:

- Current model deals with households without children by applying availability conditions.  We can just remove these households from the chooser table all together.
- Move expensive expressions to the preprocessor such as logs.

**Comment by dhensle** [comment]
Addressed with https://github.com/ActivitySim/activitysim/pull/806 and https://github.com/ActivitySim/activitysim-prototype-mtc/pull/4
