### ISSUE TITLE
Double check Sharrow memory usage fix (#751) is merged and implemented

### ISSUE THREAD

**Issue by i-am-sijia** [ActivitySim/activitysim#816]
**Describe the bug**
In Phase 8, we identified a memory usage issue in Sharrow. It was holding onto Sharrow flow data from already completed simulations. This was revealed when we compared the memory foot print of mandatory tour scheduling model of runs with vs without Sharrow. In between the simulation of tour scheduling segments (i.e., work, school, univ), the non-Sharrow run had memory released and restart from a low "base" point but the Sharrow run did not release memory and it piled up.

This was fixed in PR #751 . And at the end of the data type optimization work in Phase 8, the profiling result showed it worked. See documentation here -> https://github.com/ActivitySim/activitysim/issues/673.

In the most recent benchmarking run, it **seems** the memory of the mandatory tour scheduling is piling up again, in between its segments, and also impacting the starting point of school escorting.

![image](https://github.com/ActivitySim/activitysim/assets/28812722/3dab9b39-2fba-46a5-aabb-a1121dca11d2)

Zoomed in on Mandatory Tour Scheduling:

**Non-sharrow:**
![image](https://github.com/ActivitySim/activitysim/assets/28812722/99b863a9-b7d9-43c9-a6f2-066d4bf4e101)

**Sharrow:**
![image](https://github.com/ActivitySim/activitysim/assets/28812722/3b7b2861-d9e6-489a-832d-ccedc78cba50)

**Comment by jpn--** [comment]
I believe we have collected evidence that this actually working fine, and any apparent intermittent high(er) memory usage is likely related to the vagaries of garbage collection.
