### ISSUE TITLE
Documentation: Relative Trip Scheduling

### ISSUE THREAD

**Issue by dhensle** [ActivitySim/activitysim#823]
The following addition to models.rst explaining the relative trip scheduling logic seems to have gotten lost as I do not see it anywhere in the new documentation...? 

https://github.com/ActivitySim/activitysim/pull/657/files#diff-d606c1bcd72689c8bb949dcdafe4bcd0420da5cbaa7daf9614f0757734cffaf7

**Comment by jpn--** [comment]
That documentation now lives in the trip scheduling component documentation here:

https://github.com/ActivitySim/activitysim/blob/2f9afa0ad632d9dd3d98730c631daebb9f765b1a/docs/dev-guide/components/trip_scheduling_probabilistic.md?plain=1#L26-L34
