### ISSUE TITLE
SEMCOG model taking longer to run with 1.3 beta

### ISSUE THREAD

**Issue by aletzdy** [ActivitySim/activitysim#864]
The SEMCOG model (10%, single processed) takes longer to run with the current 1.3 beta (main branch) than the official 1.2.2 version.

I already presented on this issue last month. Adding this issue here with further log files. Key models taking longer: workplace location, non-mandatory tour scheduling, tour mode choice, and trip destination.

[activitysim_1.3beta.log](https://github.com/ActivitySim/activitysim/files/15201740/activitysim_1.3beta.log)

1.3 memory profile
<img width="1056" alt="memory_profile" src="https://github.com/ActivitySim/activitysim/assets/58451076/50ba3a96-5baf-4294-acaa-a1172aa10681">

runtime comparison between 1.2 and 1.3
![runtime_comparison](https://github.com/ActivitySim/activitysim/assets/58451076/baae64a7-dbe9-491e-be3d-4146817dc395)

**Comment by i-am-sijia** [comment]
Hi @aletzdy, do you have the activitysim.log from the equivalent 1.2 run?

**Comment by aletzdy** [comment]
[activitysim1.2.log](https://github.com/ActivitySim/activitysim/files/15221416/activitysim1.2.log)

**Comment by aletzdy** [comment]
Updating this issue regarding runtimes with and without **Sharrow**. Below is the runtime comparison of runs with following characteristics:

- full sample,
- multiporcess (20 cores),
- max ram available 500Gb and,
- run on Intel Xeon Platinum machine
- Sharrow (blue) and non-sharrow (orange). 

The runs were done last month using the main branch of ActivitySim, not camsys's sharrow-fix-all branch used for SANDAG example runs.

- Total Sharrow runtime: 252mins
- Total non-Sharrow runtime: 369mins

Workplace location is the main model taking noticeably longer under Sharrow.

![image](https://github.com/ActivitySim/activitysim/assets/58451076/4ef768ac-e6b9-4195-82de-5c2e437f4f34)

**Comment by jpn--** [comment]
Per SEMCOG, this issue is resolved.
