### ISSUE TITLE
Sharrow 2.10.0 stopped working during SEMCOG's latest ActivitySim 1.3 beta3 test 

### ISSUE THREAD

**Issue by JilanChen** [ActivitySim/activitysim#879]
**Describe the bug**
SEMCOG's ActivitySim test with Sharrow 2.9.1 worked, but when updated with the latest version 2.10.0, ActivitySim frozen during the setting up flow run of school location 

**To Reproduce**
1. Clone the latest ActivitySim - Main Branch  
2. Install the development environment (Sharrow 2.10.0 and ActivitySim 1.3 0b3.dev12)
3. Run ActivitySim with SEMCOG's input data (Sharrow on, single process, sample size of 100)  
4. Program got frozen at the following place.
![image](https://github.com/user-attachments/assets/0206b665-4212-4c83-a480-a811e150a5ba)

**Comment by jpn--** [comment]
@JilanChen, are you using the model as it appears in the ActivitySim repo [here](https://github.com/ActivitySim/activitysim/tree/main/activitysim/examples/production_semcog)?  If not please share a link or reference to a GitHub repo or similar where we can examine your model config files.

**Comment by JilanChen** [comment]
@jpn-- RSG has worked on a newer version of SEMCOG's ABM for SEMCOG's sharrow tests. It is still located at a private repo, which I can find ways to share with you as well as SEMCOG's input data used for the tests.

**Comment by JilanChen** [comment]
With uninstalling and installing the latest version again, ActivitySim runs fine with Sharrow 2.10.0 now. So I am closing this issue. Thanks, @jpn--, for your attention.
