### ISSUE TITLE
Tutorial about how activitySim works

### ISSUE THREAD

**Issue by jingjunL** [ActivitySim/activitysim#907]
**Is your feature request related to a problem? Please describe.**
I have experience using MATSim, and now I am discovering activitySim for future research. In MATSim, they have a book explaining the theoretical algorithm of the software and how it works. I only find something here: https://activitysim.github.io/activitysim/v1.3.1/howitworks.html. But I cannot really see the detailed description on this webpage.

**Describe the solution you'd like**
I believe you must have some documentation explaining the logic of the software, but unfortunately, I cannot find it. Can you share it with me if it is available?

**Comment by dhensle** [comment]
Hi @jingjunL, thanks for your interest.

We do have additional documentation on the same site you linked to above that might be what you are looking for:
* Example model documentation [here](https://activitysim.github.io/activitysim/v1.3.1/users-guide/example_models.html#example-models).
* Individual components of ActivitySim can be found [here](https://activitysim.github.io/activitysim/v1.3.1/dev-guide/components/index.html#).

If you are looking for something different or specific, please let us know.
